"""Generate the LaTeX tables and macros of the paper's simulation section.

    uv run python -m validation.paper_tables          # writes ../paper/sim/
    uv run python -m validation.paper_tables DIR      # writes DIR

Every number in `paper/simulation.tex` comes from these files, so the paper
cannot drift from the code. Scenarios and seeds are the ones in
`validation.checks`. The same run writes `paper/sim/data/*.csv`, from which
`scripts/plot_sim.py` draws the figures.
"""

from __future__ import annotations

import math
import sys
from dataclasses import dataclass
from pathlib import Path

from . import checks, seq_open, seq_price, seq_replay, workload
from .analytic import (
    agg_capacity_i,
    kingman_bound,
    mixture_utilization,
    mm1_wait,
    pk_wait,
)
from .constants import (
    CAL_DECODE_STEP,
    CAL_PREFILL_LINEAR,
    CAL_PREFILL_QUADRATIC,
    OPEN_CAP,
    OPEN_CAPS,
    OPEN_SEEDS,
    TRACE_CAP_FACTORS,
    TRACE_HORIZON,
    TRACE_PRICE_DELTAS,
    TRACE_RATES,
    TRACE_WARMUP,
)
from .dist import Deterministic, HitMiss, exp, hyperexp_balanced
from .fmt import disp, fixed, fmax, fmin, fold_max, fold_min, rround, sci_fixed, signed, ssum
from .models import agentic, eviction, pd, queue
from .models.agentic import AgenticConfig, EvictionPolicy, FetchMode, OffloadPolicy
from .models.batch import Constant
from .models.pd import Aggregated, Disaggregated
from .models.queue import QueueConfig
from .seq import REPO
from .seq_open import OpenEvictRow
from .stats import Estimate

HEADER = "% Generated by `uv run python -m validation.paper_tables` in\n% validation/. Do not edit by hand.\n"
DATA_HEADER = (
    "# Generated by `uv run python -m validation.paper_tables` in validation/. "
    "Synthetic workload; do not edit by hand.\n"
)


def pm(e: Estimate, d: int) -> str:
    return f"${fixed(e.mean, d)} \\pm {fixed(e.half_width, d)}$"


@dataclass
class Cell:
    """A table cell that can compete for "best in its group": the value as
    displayed (rounded to the printed precision) and its rendering."""

    value: float
    text: str


def cell(value: float, d: int, text: str) -> Cell:
    s = 10.0**d
    return Cell(rround(value * s) / s, text)


def bold_best(cells: list[Cell], lower_is_better: bool) -> None:
    """Bold every cell whose displayed value is the best of the group."""
    best = math.inf if lower_is_better else -math.inf
    for c in cells:
        best = fmin(best, c.value) if lower_is_better else fmax(best, c.value)
    for c in cells:
        if c.value == best:
            if c.text.startswith("$") and c.text.endswith("$"):
                c.text = f"$\\mathbf{{{c.text[1:-1]}}}$"
            else:
                c.text = f"\\textbf{{{c.text}}}"


def csv_line(fields) -> str:
    return ",".join(fields)


class Data:
    """Machine-readable copies of the table data, one per figure."""

    def __init__(self):
        self.files: list[tuple[str, str]] = []

    def push(self, name: str, header: str, rows: list[str]) -> None:
        self.files.append((name, DATA_HEADER + header + "\n" + "".join(r + "\n" for r in rows)))


def table(caption, label, cols, head, rows, colsep="3pt", size="small") -> str:
    s = HEADER
    s += "\\begin{table}[htbp]\n"
    s += f"\\caption{{{caption}}}\n"
    s += f"\\label{{{label}}}\n"
    s += f"\\centering\\{size}\\setlength{{\\tabcolsep}}{{{colsep}}}\n"
    s += f"\\begin{{tabular}}{{@{{}}{cols}@{{}}}}\n"
    s += f"\\toprule\n{head} \\\\\n\\midrule\n"
    for r in rows:
        s += f"{r} \\\\\n"
    s += "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    return s


def mg1(lam, service, customers, seed):
    return queue.simulate(QueueConfig.mg1(lam, service, customers, seed))


def in_model() -> str:
    rows = []
    r = mg1(9.0, exp(0.1), 2_000_000, 12)
    rows.append(
        f"M/M/1 $W$, $\\lambda=9$ & \\S\\ref{{sec:intro}} & {fixed(mm1_wait(10.0, 9.0), 3)} & {pm(r.sojourn, 3)}"
    )
    b = checks.WORKLOAD_B
    r = mg1(0.7, b, 2_000_000, 33)
    rows.append(
        f"PK $W_q$, workload B & Eq.~\\eqref{{eq:pk}} & {fixed(pk_wait(0.7, b.second_moment(), 0.7), 3)} & {pm(r.wait, 3)}"
    )
    wa = mg1(0.6, Deterministic(1.0), 1_000_000, 40)
    wb = mg1(0.6, b, 1_000_000, 40)
    rows.append(
        f"$W_q^B/W_q^A$, $\\rho=0.6$ & \\S\\ref{{sec:congestion}} & 3.43 & {fixed(wb.wait.mean / wa.wait.mean, 2)}"
    )
    r = mg1(1.8, HitMiss(0.8, 0.05, 0.5), 1_000_000, 54)
    rows.append(
        f"$\\rho$ at $h=0.8$ & \\S\\ref{{sec:congestion}} & {fixed(mixture_utilization(1.8, 0.8, 0.05, 0.5), 3)} & {fixed(r.utilization, 3)}"
    )
    d = HitMiss(0.96, 0.05, 5.0)
    lam = 0.5 / d.mean()
    g = mg1(lam, d, 4_000_000, 60).wait
    m = mg1(lam, exp(d.mean()), 4_000_000, 60).wait
    rows.append(
        f"$W_q$ / M/M/1, $\\mathrm{{CV}}^2{{=}}{fixed(d.cv2(), 1)}$ & \\S\\ref{{sec:congestion}} & "
        f"{fixed((1.0 + d.cv2()) / 2.0, 2)} & {fixed(g.mean / m.mean, 2)}"
    )
    mp = checks.miss_price_scenario(0.05)
    rows.append(
        f"$\\Delta L$, $\\delta=0.05$ & Prop.~\\ref{{prop:price}} & $[{fixed(mp.lo, 2)},{fixed(mp.hi, 2)}]$ & {pm(mp.dl, 3)}"
    )
    worst = 0.0
    for i, (n, c) in enumerate([(6, 20), (12, 200), (18, 60)]):
        for rr in eviction.sweep(3000, n, c, eviction.UNIFORM, 90 + i):
            worst = fmax(worst, rr.shortest_first)
    rows.append(f"max SF/OPT & Prop.~\\ref{{prop:blind}} & $\\le 2$ & {fixed(worst, 3)}")
    return table(
        "Simulation under each proposition's assumptions (in-model). "
        "M/M/1: $\\mu=10$. PK: $\\rho=0.7$. Cache: $\\lambda=1.8$. "
        "$\\Delta L$ (the prefill queue as an M/G/1 FIFO server): rise in "
        "the mean number in system when a fraction "
        "$\\delta$ of turns changes from hit ($0.05$\\,s) to miss ($0.5$\\,s) at "
        "hit rate $0.8$, $\\rho=0.6$, against the bracket "
        "$[\\lambda\\delta\\Phi,\\ \\tfrac{1-\\rho}{1-\\rho'}\\lambda\\delta\\Phi]$. "
        "SF/OPT: worst of the 9000 instances of the first three rows of "
        "Table~\\ref{tab:sim-evict}. $\\pm$ is a "
        "95\\,\\% batch-means half-width. Times in seconds.",
        "tab:sim-inmodel",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        rows,
    )


def closed() -> str:
    rows = []
    for n in (16, 32, 64, 96):
        r = agentic.simulate(AgenticConfig.example(n, 6.0e5))
        rows.append(
            f"{n} & {fixed(r.throughput, 2)} & {fixed(r.hit_rate, 2)} & {fixed(r.service.mean(), 2)} & "
            f"{fixed(r.service.cv2(), 2)} & {fixed(100.0 * r.irtl_residual(float(n)), 1)}"
        )
    return table(
        "Closed agent programs sharing one replica with a 600k-token KV pool "
        "(shortest-first eviction, no offload). The hit rate is not an input: "
        "it results from memory pressure. Last column: residual of the "
        "interactive response-time law, $|N-X(R+Z)|/N$.",
        "tab:sim-closed",
        "rccccc",
        "$N$ & $X$ (turn/s) & Hit rate & $\\E[S]$ (s) & $\\mathrm{CV}^2$ & IRTL (\\%)",
        rows,
    )


def kingman() -> str:
    s = HitMiss(0.96, 0.05, 5.0)
    rho = 0.7
    lam = rho / s.mean()
    pk = pk_wait(lam, s.second_moment(), rho)
    rows = []
    for i, ca2 in enumerate([2.0, 4.0, 8.0]):
        ia = hyperexp_balanced(1.0 / lam, ca2)
        w = queue.simulate(QueueConfig(ia, s, 1, 4_000_000, 200_000, 70 + i)).wait
        rows.append(
            f"{fixed(ca2, 0)} & {fixed(pk, 2)} & {pm(w, 2)} & {fixed(kingman_bound(lam, ia.variance(), s.variance(), rho), 2)}"
        )
    return table(
        "Bursty (hyperexponential) arrivals with the service law of "
        "\\S\\ref{sec:congestion}, $\\rho=0.7$. $c_a^2$ is the interarrival "
        "$\\mathrm{CV}^2$. Mean waits in seconds.",
        "tab:sim-kingman",
        "cccc",
        "$c_a^2$ & PK & Simulated $W_q$ & Kingman bound",
        rows,
    )


def offload() -> tuple[str, int, int]:
    rows, ok, total = [], 0, 0
    for bw in (5.0e3, 2.0e4, 1.0e5):
        for n in (32, 64):

            def run(p, n=n, bw=bw):
                return agentic.simulate(checks.offload_cfg(n, bw, p))

            nv, al, se, pr = (
                run(OffloadPolicy.Never),
                run(OffloadPolicy.Always),
                run(OffloadPolicy.Selective),
                run(OffloadPolicy.Priced),
            )
            async_cfg = checks.offload_cfg(n, bw, OffloadPolicy.Always)
            async_cfg.fetch = FetchMode.Async
            al_async = agentic.simulate(async_cfg)
            total += 1
            if se.throughput >= 0.97 * fmax(nv.throughput, al.throughput):
                ok += 1
            pols = [cell(r.throughput, 2, fixed(r.throughput, 2)) for r in (nv, al, se, pr)]
            bold_best(pols, False)
            rows.append(
                f"{fixed(bw / 1e3, 0)}k & {n} & {pols[0].text} & {pols[1].text} & {pols[2].text} & "
                f"{pols[3].text} & {fixed(al.stall_load, 2)} & {fixed(al_async.throughput, 2)} / "
                f"{fixed(al_async.response.mean(), 0)}"
            )
    t = table(
        "Offloading with blocking fetches (the replica waits for the tier). "
        "Throughput in turns/s by tier bandwidth (tokens/s), concurrency $N$ "
        "and policy; the best of the four policies per row in bold. Priced: "
        "selective with the price of a miss in place "
        "of $\\Delta S(1+Q)$ (with blocking fetches both tests reduce to "
        "transfer $<\\Delta S$). Stall: fraction of replica time spent waiting on "
        "fetches under always-offload. Last column: always-offload when "
        "fetches complete before the turn queues (asynchronous), as "
        "throughput / mean turn response time in s (including the fetch).",
        "tab:sim-offload",
        "rrcccccc",
        "Tier & $N$ & Never & Always & Selective & Priced & Stall & Async",
        rows,
    )
    return t, ok, total


def ratio(x: float, d: int) -> str:
    """A cost ratio; ratios of 1000 or more in scientific notation."""
    if x < 1000.0:
        return fixed(x, d)
    k = math.floor(math.log10(x))
    return f"${fixed(x / 10.0**k, 1)}{{\\times}}10^{{{fixed(k, 0)}}}$"


def ratio_csv(x: float) -> str:
    """A ratio for the CSV files: plain decimals, scientific past 10^4."""
    return fixed(x, 5) if x < 1.0e4 else sci_fixed(x, 4)


OFFLINE_POLICIES = [
    ("SF", lambda r: r.shortest_first),
    ("Density", lambda r: r.density_first),
    ("Guarded", lambda r: r.guarded_density),
]


def evict_offline(data: Data) -> str:
    sweeps = []
    for name, id_, rm, seed in [
        ("equal $p_i$", "equal_p", eviction.UNIFORM, 5),
        ("$p_i\\sim U[0.05,1]$", "varied_p", eviction.varied(0.05), 99),
        ("$p_i$ falls with $c_i$", "p_falls_with_c", eviction.SHORTER_RESUMES, 7),
    ]:
        sweeps.append((name, id_, eviction.sweep(3000, 12, 200, rm, seed)))
    sweeps.append(("arbitrary $w_i$", "arbitrary_w", eviction.sweep_weighted(3000, 12, 200, 161)))
    rows, summary, samples = [], [], []
    for name, id_, v in sweeps:
        means, maxes = [], []
        for pol, f in OFFLINE_POLICIES:
            vals = [f(r) for r in v]
            mean = ssum(vals) / len(v)
            mx = fold_max(vals, 0.0)
            means.append(cell(mean, 3, ratio(mean, 3)))
            maxes.append(cell(mx, 2, ratio(mx, 2)))
            summary.append(csv_line([id_, pol, ratio_csv(mean), ratio_csv(mx)]))
        bold_best(means, True)
        bold_best(maxes, True)
        cells = [f"{m.text} / {x.text}" for m, x in zip(means, maxes, strict=True)]
        rows.append(f"{name} & {' & '.join(cells)}")
        for i, r in enumerate(v):
            samples.append(
                csv_line(
                    [
                        id_,
                        str(i),
                        ratio_csv(r.shortest_first),
                        ratio_csv(r.density_first),
                        ratio_csv(r.guarded_density),
                    ]
                )
            )
    data.push("evict-offline.csv", "regime,policy,mean_cost_over_opt,max_cost_over_opt", summary)
    data.push("evict-offline-samples.csv", "regime,instance,sf,density,guarded", samples)
    return table(
        "Offline eviction: cost relative to the exact optimum of "
        "\\eqref{eq:evict-priced}, mean / max over 3000 random instances per row "
        "(12 programs, $c_i\\in\\{1,\\dots,200\\}$, $\\Delta C$ a random "
        "10--60\\,\\% of the total); the lowest mean and the lowest max per "
        "row in bold. First three rows: costs $p_ic_i^2$. "
        "Last row: weights $w_i$ log-uniform on $[10^{-4},10^5]$, independent "
        "of $c_i$; shortest-first does not see $w_i$ there, and its ratio is "
        "the price of ignoring the weights. Guarded: the guarded density greedy "
        "of \\S\\ref{sec:evict}.",
        "tab:sim-evict",
        "lccc",
        "Costs & SF & Density & Guarded",
        rows,
    )


def ps_table() -> str:
    rows = []
    ins = checks.insensitivity_scenario()
    for r in ins:
        rows.append(
            f"PS, {r.name} & \\S\\ref{{sec:batch}} & {fixed(r.ps_theory, 3)} & {pm(r.ps, 3)}"
        )
    for r in ins:
        rows.append(
            f"FIFO, {r.name} & Eq.~\\eqref{{eq:pk}} & {fixed(r.fifo_theory, 3)} & {pm(r.fifo, 3)}"
        )
    for r in checks.bcmp_scenario():
        if isinstance(r.phi, Constant):
            phi = f"$\\phi\\equiv{disp(r.phi.c)}$"
        else:
            phi = f"sat.\\ $\\phi$ ($\\beta{{=}}{disp(r.phi.beta)}$)"
        rows.append(
            f"Loop, {phi} & \\S\\ref{{sec:sessions}} & {fixed(r.theory, 2)} & {pm(r.sim, 2)}"
        )
    m = checks.ps_price_scenario(0.05)
    rows.append(
        f"PS $\\Delta L$, $\\delta{{=}}0.05$ & Prop.~\\ref{{prop:decode}} & $[{fixed(m.lo, 2)},{fixed(m.hi, 2)}]$ & {pm(m.dl, 3)}"
    )
    t = seq_price.price_scenario(0.05)
    rows.append(
        f"vLLM $\\Delta L_P$, $\\delta{{=}}0.05$ & Prop.~\\ref{{prop:price}} & $[{fixed(t.lo, 2)},{fixed(t.hi, 2)}]$ & {pm(t.dl_p, 3)}"
    )
    rows.append(
        f"vLLM $\\Delta L_D$, $\\delta{{=}}0.05$ & Prop.~\\ref{{prop:decode}} & 0 & {pm(t.dl_d, 3)}"
    )
    return table(
        "Batching server under its assumptions (in-model): mean number of "
        "turns at the replica, $L=\\lambda R$. Rows 1--4: Poisson turns at "
        "$\\rho=0.7$, work deterministic or hit/miss ($0.05$\\,s w.p.\\ $0.8$, "
        "else $0.5$\\,s; both mean $0.14$\\,s); PS theory $\\rho/(1-\\rho)$, "
        "FIFO theory $\\lambda W_q+\\rho$. Rows 5--6: sessions arrive Poisson, "
        "each turn is followed by a tool call (mean 2\\,s, $\\mathrm{CV}^2=4$) "
        "and another turn w.p.\\ $0.8$; theory $\\sum_n n\\pi(n)$ at "
        "$\\lambda=\\Lambda/(1-p)$ ($\\rho=0.7$ for $\\phi\\equiv 1$, $\\rho=3$ "
        "for $\\phi(n)=n/(1+\\beta(n-1))$). Row 7: rise of $L$ at a PS "
        "server when a fraction $\\delta$ of turns becomes misses, hit rate "
        "$0.8$, $\\rho=0.6$, against $[\\lambda\\delta\\Phi_{\\mathrm{PS}},\\ "
        "\\tfrac{C-\\rho}{C-\\rho'}\\lambda\\delta\\Phi_{\\mathrm{PS}}]$. "
        "Rows 8--9 (beyond the model): the same misses on a replica with the "
        "vLLM~v1 engine's rules and the testbed's cost model (prefill of "
        "512 or 5120 tokens in the budget a decode batch of 8 tokens per turn "
        f"leaves, mean availability $\\bar r={fixed(t.avail, 3)}$, $\\lambda\\E[P]=0.6$): rise "
        "of the number in the prefill stage $L_P=\\lambda\\,\\mathrm{TTFT}$ "
        "against the FIFO bracket at service $P/\\bar r$, and of the number in "
        "the decode stage $L_D$, whose demand does not depend on hit or miss "
        "but whose iterations a miss's prefill lengthens. $\\pm$ is a "
        "95\\,\\% batch-means half-width.",
        "tab:sim-ps",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        rows,
    )


def footprint_table() -> str:
    rows = [f"{r.law} & {fixed(r.theory, 4)} & {pm(r.sim, 4)}" for r in checks.footprint_scenario()]
    return table(
        "Expected number of requests admitted in arrival order into $M=12$ "
        "tokens of KV until the first that does not fit "
        "(\\S\\ref{sec:batch}). Footprints $K$ i.i.d.; the two laws in "
        "each pair have the same mean. Simulated: $10^6$ draws, $\\pm$ a "
        "95\\,\\% half-width.",
        "tab:sim-footprint",
        "lcc",
        "Footprint & Theory & Simulated",
        rows,
    )


def lps_table(data: Data) -> str:
    sc = checks.lps_scenario()
    rows, csv = [], []
    for r in sc:
        err = 100.0 * (r.lps.mean / r.theory - 1.0)
        rows.append(
            f"{r.service} ({fixed(r.cv2, 0)}) & {fixed(r.u, 1)} & {fixed(r.theory, 2)} & {pm(r.ps, 2)} & "
            f"{pm(r.lps, 2)} & ${signed(err, 0)}$"
        )
        csv.append(
            csv_line(
                [
                    r.service, fixed(r.cv2, 1), fixed(r.u, 2), fixed(r.theory, 4), fixed(r.ps.mean, 4),
                    fixed(r.ps.half_width, 4), fixed(r.lps.mean, 4), fixed(r.lps.half_width, 4),
                    fixed(err, 3), fixed(100.0 * r.lps.half_width / r.theory, 3),
                ]
            )
        )  # fmt: skip
    data.push("lps.csv", "work,cv2,u,formula,ps,ps_hw,lps,lps_hw,err_pct,err_pct_hw", csv)
    return table(
        f"Batch cap $B={checks.LPS_CAP}$: exact limited PS (at most $B$ turns share "
        f"$\\phi(n)=n/(1+{disp(checks.LPS_BETA)}(n-1))$, FIFO beyond) against PS with $\\phi$ "
        "flattened at $B$, the model's approximation. Poisson turns, work of "
        "mean 1 with the given law ($\\mathrm{CV}^2$ in brackets), load "
        "$u=\\rho/\\phi(B)$. Mean number at the replica; last column: "
        "relative error of the approximation for LPS, in \\%. Mean "
        "response time has the same relative error (Little).",
        "tab:sim-lps",
        "lccccc",
        "Work & $u$ & Formula & PS & LPS & Err.",
        rows,
    )


E = EvictionPolicy
POLICY_NAME = {
    E.ShortestFirst: "SF",
    E.Lru: "LRU",
    E.Density: "Density",
    E.Priced: "Priced",
    E.PricedMemory: "Priced/$\\tau$",
    E.PricedMemoryBlocks: "Blocks",
}
POLICY_ID = {
    E.ShortestFirst: "SF",
    E.Lru: "LRU",
    E.Density: "Density",
    E.Priced: "Priced",
    E.PricedMemory: "PricedTau",
    E.PricedMemoryBlocks: "Blocks",
}
OPEN_WORKLOAD = (
    "Sessions arrive Poisson at rate $\\Lambda$ (per s): half agents "
    "($p_i=0.95$, 4--8k initial tokens, tool calls Exp(6\\,s)), half one-shot "
    "documents ($p_i=0.3$, 15--30k tokens, think time Exp(2\\,s)); 600k-token "
    "KV, batch cap 8"
)
OPEN_CSV_HEADER = (
    "rate,cap,policy,throughput,throughput_hw,hit,hit_hw,"
    "ttft,ttft_hw,ttft_p99,ttft_p99_hw,response,response_hw,"
    "entry_wait,entry_wait_hw,thrashed,seeds"
)


def open_policy_label(r: OpenEvictRow) -> str:
    return POLICY_NAME[r.policy] if r.end_known else f"{POLICY_NAME[r.policy]}$^*$"


def open_policy_id(r: OpenEvictRow) -> str:
    return POLICY_ID[r.policy] if r.end_known else f"{POLICY_ID[r.policy]}-end-unknown"


def open_csv_line(r: OpenEvictRow) -> str:
    f = [fixed(r.rate, 2), str(r.cap), open_policy_id(r)]
    for e in (r.throughput, r.hit_rate, r.ttft, r.ttft_p99, r.response, r.entry_wait):
        f += [fixed(e.mean, 4), fixed(e.half_width, 4)]
    f += [str(r.collapsed), str(OPEN_SEEDS)]
    return csv_line(f)


def open_group_rows(group: list[OpenEvictRow], render) -> list[str]:
    """Rows of one (Λ, cap) group with the best value per metric in bold:
    X (max), hit (max), TTFT (min, with and without its half-width), p99 (min)."""

    def col(f, d, with_hw):
        return [cell(f(r).mean, d, pm(f(r), d) if with_hw else fixed(f(r).mean, d)) for r in group]

    x = col(lambda r: r.throughput, 2, False)
    hit = col(lambda r: r.hit_rate, 2, False)
    ttft_pm = col(lambda r: r.ttft, 2, True)
    ttft = col(lambda r: r.ttft, 2, False)
    p99 = col(lambda r: r.ttft_p99, 1, False)
    bold_best(x, False)
    bold_best(hit, False)
    bold_best(ttft_pm, True)
    bold_best(ttft, True)
    bold_best(p99, True)
    return [
        render(r, [x[i].text, hit[i].text, ttft_pm[i].text, ttft[i].text, p99[i].text])
        for i, r in enumerate(group)
    ]


def evict_open(open_rows, data: Data) -> str:
    rows, csv = [], []
    for rate in seq_open.RATES:
        group = [r for r in open_rows if r.cap == OPEN_CAP and r.rate == rate]
        rows += open_group_rows(
            group,
            lambda r, c: (
                f"{fixed(r.rate, 2)} & {open_policy_label(r)} & {c[0]} & {c[1]} & {c[2]} & {c[4]} & "
                f"{fixed(r.response.mean, 1)} & {r.collapsed}"
            ),
        )
        csv += [open_csv_line(r) for r in group]
    data.push("evict-dyn.csv", OPEN_CSV_HEADER, csv)
    return table(
        "Eviction with open sessions on a replica with the vLLM~v1 engine's "
        "rules (those of Table~\\ref{tab:sim-trace}) and the testbed's cost "
        f"model. {OPEN_WORKLOAD}, at most {OPEN_CAP} live sessions. Every policy evicts "
        "16-token blocks from the tail of a context, sessions in a tool call "
        "before waiting ones (except LRU), and drops a finished session's "
        "blocks; rows marked $^*$ keep them, as vLLM's engine does, which "
        "cannot tell a finished session from one in a tool call. Throughput "
        "(turns/s), follow-up hit rate (the whole reusable prefix reused), "
        "mean and p99 time to first token (s), mean turn response (s; its "
        "half-width is in the data file), and "
        f"the number of the {OPEN_SEEDS} seeds that thrashed (follow-up turns reusing less "
        "than half of their reusable prefix); "
        "$\\pm$ is a 95\\,\\% half-width over seeds; the best throughput, hit "
        "rate, TTFT and p99 per load in bold. Priced: $p_i\\Phi_i/c_i$ with "
        "the FIFO price of Prop.~\\ref{prop:price} from online estimates at "
        "the engine; Priced/$\\tau$: per byte-second, "
        "$p_i\\Phi_i/(c_i\\tau_i)$ (the threshold rule of "
        "\\S\\ref{sec:evict}); Blocks: the same price of the tail block. The "
        "priced rules take $p_i$ and $\\tau_i$ from the generating class (an "
        "oracle); the fixed keys see neither.",
        "tab:sim-evict-dyn",
        "clcccccc",
        "$\\Lambda$ & Policy & $X$ & Hit & TTFT & p99 & $R$ & Thr.",
        rows,
        "2pt",
    )


def admission_table(open_rows, data: Data) -> str:
    rows, csv = [], []
    for cap in OPEN_CAPS:
        for rate in seq_open.RATES:
            group = [
                next(
                    r
                    for r in open_rows
                    if r.cap == cap and r.rate == rate and r.policy == pol and r.end_known
                )
                for pol in seq_open.SWEEP
            ]
            rows += open_group_rows(
                group,
                lambda r, c, cap=cap: (
                    f"{fixed(r.rate, 2)} & {cap} & {POLICY_NAME[r.policy]} & {c[0]} & {c[1]} & {c[3]} & "
                    f"{c[4]} & {fixed(r.response.mean, 2)} & {fixed(r.entry_wait.mean, 1)} & {r.collapsed}"
                ),
            )
            csv += [open_csv_line(r) for r in group]
    data.push("admission.csv", OPEN_CSV_HEADER, csv)
    return table(
        "Admission-cap sweep on the vLLM-rule replica: the scenario of "
        "Table~\\ref{tab:sim-evict-dyn} with at most 16, 24 or 32 live "
        "sessions; later arrivals wait in an entry queue. Throughput "
        "(turns/s), follow-up hit rate, mean and p99 time to first token "
        "(s), mean turn response (s), mean entry-queue wait of a new "
        f"session (s), and the number of the {OPEN_SEEDS} seeds that thrashed. Means "
        "over seeds; the best throughput, hit rate, TTFT and p99 per "
        "($\\Lambda$, cap) in bold. The 95\\,\\% half-widths over seeds "
        "are the whiskers of Figure~\\ref{fig:sim-admission}; "
        "Table~\\ref{tab:sim-evict-dyn} states them for the rows it "
        "shares. An entry wait of hundreds of "
        "seconds means the replica does not carry the offered turn rate "
        "and the entry queue grows over the run; such values depend on "
        "the horizon (20\\,000\\,s). Every policy drops a finished session's "
        "blocks.",
        "tab:sim-admission",
        "ccl@{\\hspace{3pt}}cccccccc",
        "$\\Lambda$ & Cap & Policy & $X$ & Hit & TTFT & p99 & $R$ & Entry & Thr.",
        rows,
        "2pt",
    )


INVERSION_CSV_HEADER = "bandwidth,move_over_service,rho_star,inversion_rate,hot_utilization,link_utilization,affinity,always_move,lookahead"


def _opt(v, d):
    return "--" if v is None else fixed(v, d)


def _optd(v):
    return disp(math.nan if v is None else v)


def inversion_table(data: Data) -> str:
    rows, csv = [], []
    for r in checks.inversion_scenario():
        if r.inversion_rate is not None and r.inversion_rate <= checks.INVERSION_RATES[0] + 1e-9:
            inv = f"$\\le {fixed(r.inversion_rate, 2)}$"
        else:
            inv = _opt(r.inversion_rate, 2)
        rows.append(
            f"{fixed(r.bandwidth / 1e3, 0)}k & {fixed(r.move_over_service, 2)} & {fixed(r.rho_star, 2)} & {inv} & "
            f"{_opt(r.hot_utilization, 2)} & {_opt(r.link_utilization, 2)} & {_opt(r.affinity_response, 3)} & "
            f"{_opt(r.move_response, 3)} & {_opt(r.lookahead_response, 3)}"
        )
        csv.append(
            ",".join(
                [disp(r.bandwidth), disp(r.move_over_service), disp(r.rho_star)]
                + [
                    _optd(v)
                    for v in (
                        r.inversion_rate,
                        r.hot_utilization,
                        r.link_utilization,
                        r.affinity_response,
                        r.move_response,
                        r.lookahead_response,
                    )
                ]  # fmt: skip
            )
        )
    data.push("inversion.csv", INVERSION_CSV_HEADER, csv)
    return table(
        "Placement over 4 replicas with half of the new programs placed on "
        "replica~0 (the affinity node), follow-up turns of 5--15k-token contexts, "
        "state moved over one shared link of bandwidth $B$ (tokens/s) when that is "
        "cheaper than recomputing it. $x$: mean move cost over mean service; "
        "$\\rho^*=x/(1+x)$, the inversion utilisation of Eq.~\\eqref{eq:rhostar} "
        "for one node and an idle alternative; Inv.: the lowest program rate (per s, "
        "swept in steps of 0.05) at which always moving to the least-loaded replica "
        "beats affinity in mean turn response beyond both confidence intervals; "
        "$\\rho_0$: utilisation of the affinity node at that rate; $\\rho_L$: "
        "utilisation of the shared link under always-move there; mean turn response "
        "(s) of affinity, always-move and the lookahead rule of "
        "Eq.~\\eqref{eq:lookahead}. The idle alternative gives the earliest "
        "inversion, so $\\rho^*$ is a lower bound for any real alternative.",
        "tab:sim-inversion",
        "ccccccccc",
        "$B$ & $x$ & $\\rho^*$ & Inv. & $\\rho_0$ & $\\rho_L$ & Affinity & Move & Lookahead",
        rows,
        "2pt",
        "scriptsize",
    )


def pd_in_model() -> str:
    rows = []
    agg = pd.simulate(checks.pd_cfg(32, Aggregated(), 1.0, 1.0, 0.5, (2.0, 1.0), 1000.0))
    rows.append(
        f"$\\mu_A$, $I=0.5$ & Prop.~\\ref{{prop:pd}} & {fixed(agg_capacity_i(32.0, 1.0, 1.0, 0.5), 2)} & {fixed(agg.throughput, 2)}"
    )
    cfg = checks.pd_cfg(32, Disaggregated(11), 1.0, 1.0, 0.5, (2.0, 1.0), 1000.0)
    r = pd.simulate(cfg)
    rows.append(
        f"$\\mu_{{PD}}$, $N_P=11$ & Prop.~\\ref{{prop:pd}} & {fixed(pd.split_capacity(cfg, 11), 2)} & {fixed(r.throughput, 2)}"
    )
    return table(
        "Scalar PD capacities under the assumptions of "
        "Prop.~\\ref{prop:pd} (in-model): $N=32$, $s_P=s_D=1$, $g_P=2$. "
        "Capacities in requests per second.",
        "tab:sim-pd-inmodel",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        rows,
    )


def pd_latency() -> str:
    rows = []
    for rate in (1.0, 1.6, 1.9):
        ra, rd = checks.pd_latency_pair(rate)
        rows.append(f"{fixed(rate, 1)} & {pm(ra.latency, 2)} & {pm(rd.latency, 2)}")
    return table(
        "Latency at equal capacity: $N=8$, $s_P=1$, $s_D=3$, no gains or "
        "interference, rate-matched split $N_P=2$. Both configurations have "
        "capacity 2 requests/s. Mean end-to-end latency (s).",
        "tab:sim-pd",
        "ccc",
        "$\\lambda$ & Aggregated & PD ($N_P=2$)",
        rows,
    )


TRACE_CSV_HEADER = (
    "rate,pool,cap,hit,hit_hw,reused,reused_hw,sessions,entry_wait,rho,cv2,"
    "mixture_share,mixture_share_hw,wait,pk_wait,ttft,ttft_hw,ttft_p99,prefill_number,seeds"
)


def trace_table(rows_all, data: Data) -> str:
    corpus = workload.weka()
    rows, csv = [], []
    for r in rows_all:
        pool = f"{fixed(r.kv / 1e6, 0)}M" if math.isfinite(r.kv) else "$\\infty$"
        regime = f"$N{{=}}{r.cap}$" if math.isfinite(r.kv) else f"$\\Lambda{{=}}{disp(r.rate)}$"
        rows.append(
            f"{pool} & {regime} & {fixed(r.sessions.mean, 1)} & {fixed(r.throughput.mean, 3)} & "
            f"{fixed(r.hit_rate.mean, 2)} & {fixed(r.reused.mean, 2)} & {fixed(r.mixture_share.mean, 2)} & "
            f"{fixed(r.cv2.mean, 1)} & {fixed(r.rho.mean, 2)} & {fixed(r.wait.mean, 0)} & "
            f"{fixed(r.pk_wait.mean, 0)} & {fixed(r.ttft.mean, 0)}"
        )
        csv.append(
            ",".join(
                [disp(r.rate), disp(r.kv), str(r.cap)]
                + [
                    disp(x)
                    for x in (
                        r.hit_rate.mean,
                        r.hit_rate.half_width,
                        r.reused.mean,
                        r.reused.half_width,
                        r.sessions.mean,
                        r.entry_wait.mean,
                        r.rho.mean,
                        r.cv2.mean,
                        r.mixture_share.mean,
                        r.mixture_share.half_width,
                        r.wait.mean,
                        r.pk_wait.mean,
                        r.ttft.mean,
                        r.ttft.half_width,
                        r.ttft_p99.mean,
                        r.prefill_number.mean,
                    )
                ]  # fmt: skip
                + [str(seq_replay.SEEDS)]
            )
        )
    data.push("trace.csv", TRACE_CSV_HEADER, csv)
    return table(
        "Replayed production sessions on a replica with the vLLM~v1 engine's "
        f"rules: {len(corpus.sessions)} Claude Code sessions ({corpus.turns()} turns, mean final context "
        f"{fixed(corpus.mean_final_context() / 1e3, 0)}k tokens, "
        f"mean think time {fixed(corpus.mean_think(), 0)}\\,s; a gap above 10\\,min starts a new session) from the "
        "corpus of \\S\\ref{sec:exp-traces}, each played turn by turn. The engine "
        "admits a waiting turn at the start of an iteration with the token budget its "
        "residents leave, once its whole prompt fits, and grows its KV chunk by chunk (a "
        "growth that does not fit preempts the latest admitted turn); KV is cached in "
        "16-token blocks, evicted from the tail of a context by price per byte-second "
        "where the pool is finite; a finished session's blocks stay. Cost model with "
        f"$K_c=a/b\\approx{fixed(CAL_PREFILL_LINEAR / CAL_PREFILL_QUADRATIC / 1e3, 0)}$k tokens (calibrated on the testbed), batch cap 8. "
        "With no pool limit the replica is open (Poisson sessions at rate "
        "$\\Lambda$ per s, at most 24 live; the regime column gives $\\Lambda$). With a finite pool the cap on live "
        "sessions binds throughout the run, so the replica is a closed system of "
        "$N$ sessions and the arrival rate is immaterial; the entry queue grows "
        "for the whole horizon. Mean live sessions $\\bar N$ and throughput $X$ "
        "(turns/s); follow-up hit rate (the whole reusable prefix reused) and the "
        "mean share of the reusable prefix reused (Reuse); "
        "the share of $\\mathrm{Var}[S]$ of follow-up prefill work due to the "
        "hit/miss mixture (the rest is the spread of the appends and of partial "
        "misses) and the "
        "$\\mathrm{CV}^2$ of that work; prefill load $\\rho$ in stage time; observed "
        "mean prefill wait $W_q$ and the PK wait from the measured $\\lambda$, "
        f"$\\E[S]$, $\\E[S^2]$ (s); mean TTFT (s). Means over {seq_replay.SEEDS} seeds; the "
        "half-widths are in the data file.",
        "tab:sim-trace",
        "clcccccccccc",
        "Pool & Regime & $\\bar N$ & $X$ & Hit & Reuse & Mix & $\\mathrm{{CV}}^2$ & $\\rho$ & $W_q$ & PK & TTFT",
        rows,
        "1.5pt",
        "scriptsize",
    )


def finite_source_table(data: Data) -> str:
    rows, csv = [], []
    for r in checks.finite_source_scenario():
        rows.append(
            f"{r.n} & {fixed(r.think, 1)} & {fixed(r.wait_exact, 3)} & "
            f"{pm(Estimate(r.wait_sim.mean - 1.0, r.wait_sim.half_width), 3)} & {fixed(r.wait_open, 3)} & "
            f"{fixed(r.wait_open / r.wait_exact, 2)}"
        )
        csv.append(
            ",".join(
                [str(r.n)]
                + [
                    disp(x)
                    for x in (
                        r.think,
                        r.rho,
                        r.wait_exact,
                        r.wait_sim.mean - 1.0,
                        r.wait_sim.half_width,
                        r.wait_open,
                    )
                ]
            )
        )
    data.push("finite-source.csv", "n,think,rho,wait_exact,wait_sim,wait_sim_hw,wait_open", csv)
    return table(
        "A FIFO prefill queue fed by $N$ live sessions, each thinking for an "
        "exponential time of mean $Z$ (s) and then submitting a turn of exponential "
        "work with mean $1$\\,s, with $Z$ chosen so that the server utilisation is "
        f"$\\rho={disp(checks.FINITE_SOURCE_RHO)}$ for every $N$. Mean wait in queue (s): exact finite-source value "
        "(M/M/1//$N$), simulated (95\\,\\% batch-means half-width), and the open "
        "M/M/1 wait $\\rho/(\\mu(1-\\rho))$ that the PK formula gives from the "
        "measured rate and moments; last column their ratio.",
        "tab:sim-finite",
        "cccccc",
        "$N$ & $Z$ & Exact & Simulated & Open & Open/Exact",
        rows,
    )


TRACE_PRICE_CSV_HEADER = "rate,delta,rho,rho1,live,live1,l_p,hit,dl_p,dl_p_hw,lo,hi,finite,seeds"


def trace_price_table(rows_all, data: Data) -> str:
    rows, csv = [], []
    for r in rows_all:
        hi = fixed(r.hi, 1) if math.isfinite(r.hi) else "$\\rho'\\ge1$"
        rows.append(
            f"{disp(r.rate)} & {fixed(r.delta, 2)} & {fixed(r.live, 1)} & {fixed(r.live1, 1)} & "
            f"{fixed(r.rho, 2)} & {fixed(r.rho1, 2)} & {fixed(r.l_p, 1)} & {pm(r.dl_p, 1)} & "
            f"{fixed(r.lo, 1)} & {hi} & {fixed(r.finite, 1)} & {fixed(r.live1 - r.l_p, 1)}"
        )
        csv.append(
            ",".join(
                [
                    disp(x)
                    for x in (
                        r.rate,
                        r.delta,
                        r.rho,
                        r.rho1,
                        r.live,
                        r.live1,
                        r.l_p,
                        r.hit_rate,
                        r.dl_p.mean,
                        r.dl_p.half_width,
                        r.lo,
                        r.hi,
                        r.finite,
                    )
                ]  # fmt: skip
                + [str(seq_replay.PRICE_SEEDS)]
            )
        )
    data.push("trace-price.csv", TRACE_PRICE_CSV_HEADER, csv)
    return table(
        "Forced misses on the replayed production sessions with no pool limit "
        "(open, Poisson sessions at rate $\\Lambda$ per s, at most 24 live, "
        f"{fixed(TRACE_HORIZON - TRACE_WARMUP, 0)}\\,s of measurement after {fixed(TRACE_WARMUP, 0)}\\,s of warm-up: the configuration of "
        "the first rows of Table~\\ref{tab:sim-trace}). A share $\\delta$ of "
        "follow-up turns is forced to miss: the turn reuses nothing, as a nonce at the "
        "head of its prompt would make it, and its old blocks stay cached. $\\bar N$, "
        "$\\bar N'$: mean live sessions in the baseline and in the forced run; "
        "$\\rho$: prefill load of the baseline; $\\rho'$: the load the added work "
        "implies; $L_P$: baseline mean number in the prefill stage; $\\Delta L_P$: "
        f"its rise in the forced run, mean and 95\\,\\% half-width over {seq_replay.PRICE_SEEDS} seeds; "
        "$[\\mathrm{lo},\\mathrm{hi}]$: the bracket of "
        "Proposition~\\ref{prop:price} from the baseline's measured $\\lambda$, "
        "$\\rho$, $W$ and each forced turn's own $S^{\\mathrm{hit}}$, "
        "$S^{\\mathrm{miss}}$ ($\\rho'\\ge1$: the open queue would be unstable); "
        "Finite: the rise of Proposition~\\ref{prop:finite}'s recursion for the "
        "added mean work, with $N=\\bar N$ rounded and the corpus mean think time; "
        "Fin.: that finite-source rise; cap: $\\bar N'-L_P$.",
        "tab:sim-trace-price",
        "cccccccccccc",
        "$\\Lambda$ & $\\delta$ & $\\bar N$ & $\\bar N'$ & $\\rho$ & $\\rho'$ & $L_P$ & $\\Delta L_P$ & lo & hi & Fin. & cap",
        rows,
        "2pt",
        "scriptsize",
    )


def trace_split_table() -> str:
    rows = []
    corpora = [workload.weka(), workload.weka_split_30min()]
    for (name, r, turns, think), c in zip(seq_replay.trace_split_scenario(), corpora, strict=True):
        rows.append(
            f"{name} & {len(c.sessions)} & {fixed(turns, 1)} & {fixed(think, 0)} & {fixed(r.sessions.mean, 1)} & "
            f"{fixed(r.throughput.mean, 3)} & {fixed(r.cv2.mean, 1)} & {fixed(r.rho.mean, 2)} & "
            f"{fixed(r.wait.mean, 0)} & {fixed(r.pk_wait.mean, 0)} & {fixed(r.ttft.mean, 0)}"
        )
    return table(
        f"Sensitivity of the open-pool replay ($\\Lambda={disp(TRACE_RATES[0])}$, no pool limit) to "
        "the rule that starts a new session at a gap longer than the threshold: "
        "sessions in the corpus, mean turns and mean think time (s) per session, "
        "then mean live sessions, throughput (turns/s), follow-up prefill-work "
        "$\\mathrm{CV}^2$, load, observed and PK prefill wait (s) and mean TTFT (s).",
        "tab:sim-trace-split",
        "lcccccccccc",
        "Split & Sess. & Turns & Think & $\\bar N$ & $X$ & $\\mathrm{{CV}}^2$ & $\\rho$ & $W_q$ & PK & TTFT",
        rows,
        "1pt",
        "scriptsize",
    )


def _fmin(xs):
    return fold_min(xs)


def _fmax(xs):
    return fold_max(xs)


def macros(all_checks, open_rows, trace_rows, price_rows, offload_ok, offload_cells) -> str:
    passed = sum(1 for c in all_checks if c.passed)
    pd_check = next(c for c in all_checks if c.id == "pd_win_condition_decisions")
    agree, total = pd_check.observed.split()[0].split("/")
    m = [HEADER.rstrip("\n")]

    def cmd(name, value):
        m.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    cmd("simChecks", len(all_checks))
    cmd("simCalA", fixed(CAL_PREFILL_LINEAR * 1e3, 3))
    cmd("simCalB", fixed(CAL_PREFILL_QUADRATIC * 1e9, 2))
    cmd("simCalOmega", fixed(CAL_DECODE_STEP, 3))
    cmd("simChecksPassed", passed)
    pct = 0.0
    for d in (0.01, 0.05):
        r = seq_price.price_scenario(d)
        pct = fmax(pct, 100.0 * abs(r.dl_d.mean) / r.l_d.mean)
    cmd("simDecodeShiftPct", fixed(pct, 1))

    def at(rate, pol, end):
        return next(
            r
            for r in open_rows
            if r.cap == OPEN_CAP and r.rate == rate and r.policy == pol and r.end_known == end
        )

    ratios = []
    for rate in seq_open.RATES:
        best = _fmin(at(rate, p, True).ttft.mean for p in seq_open.POLICIES if p != E.Lru)
        ratios.append(at(rate, E.Lru, True).ttft.mean / best)
    cmd("simEvictLruRatioMin", fixed(_fmin(ratios), 1))
    cmd("simEvictLruRatioMax", fixed(_fmax(ratios), 1))
    r0 = seq_open.RATES[0]
    known, unknown = at(r0, E.PricedMemory, True), at(r0, E.PricedMemory, False)
    cmd("simEndUnknownHit", fixed(unknown.hit_rate.mean, 2))
    cmd("simEndKnownHit", fixed(known.hit_rate.mean, 2))
    cmd("simEndUnknownTtftRatio", fixed(unknown.ttft.mean / known.ttft.mean, 1))
    cmd("simPdAgree", agree)
    cmd("simPdCells", total)
    cmd("simOffloadOk", offload_ok)
    cmd("simOffloadCells", offload_cells)
    corpus = workload.weka()
    ratio_ = [r.pk_wait.mean / r.wait.mean for r in trace_rows]
    tight = [
        r for r in trace_rows
        if math.isfinite(r.kv) and r.cap == seq_replay.trace_cap(corpus, r.kv, TRACE_CAP_FACTORS[0])
    ]  # fmt: skip
    loose = [
        r for r in trace_rows
        if math.isfinite(r.kv) and r.cap == seq_replay.trace_cap(corpus, r.kv, TRACE_CAP_FACTORS[1])
    ]  # fmt: skip
    open_ = [r for r in trace_rows if not math.isfinite(r.kv)]
    cmd("simTracePkRatioMin", fixed(_fmin(ratio_), 0))
    cmd("simTracePkRatioMax", fixed(_fmax(ratio_), 0))
    cmd("simTraceOpenCvMin", fixed(_fmin(r.cv2.mean for r in open_), 0))
    cmd("simTraceOpenCvMax", fixed(_fmax(r.cv2.mean for r in open_), 0))
    cmd("simTraceOpenTtftMin", fixed(_fmin(r.ttft.mean for r in open_), 0))
    cmd("simTraceOpenTtftMax", fixed(_fmax(r.ttft.mean for r in open_), 0))
    cmd("simTraceTightHitMin", fixed(_fmin(r.hit_rate.mean for r in tight), 2))
    cmd("simTraceTightReusedMin", fixed(_fmin(r.reused.mean for r in tight), 2))
    cmd("simTraceTightMixMin", fixed(100.0 * _fmin(r.mixture_share.mean for r in tight), 0))
    cmd("simTraceTightMixMax", fixed(100.0 * _fmax(r.mixture_share.mean for r in tight), 0))
    cmd("simTraceLooseHitMax", fixed(_fmax(r.hit_rate.mean for r in loose), 2))
    cmd("simTraceLooseTtftMin", fixed(_fmin(r.ttft.mean for r in loose), 0))
    cmd("simTraceSessions", len(corpus.sessions))
    cmd("simTraceEntryMaxHours", fixed(_fmax(r.entry_wait.mean / 3600.0 for r in trace_rows), 0))
    small = [r.dl_p.mean / r.lo for r in price_rows if r.delta <= 0.03]
    large = [r.dl_p.mean / r.lo for r in price_rows if r.delta > 0.03]
    cmd("simPriceSmallRatioMin", fixed(_fmin(small), 2))
    cmd("simPriceSmallRatioMax", fixed(_fmax(small), 2))
    cmd("simPriceLargeRatioMin", fixed(_fmin(large), 1))
    cmd("simPriceLargeRatioMax", fixed(_fmax(large), 1))
    cmd("simPriceLiveMin", fixed(_fmin(r.live for r in price_rows), 0))
    cmd("simPriceLiveMax", fixed(_fmax(r.live for r in price_rows), 0))
    fin_ratio = [r.dl_p.mean / r.finite for r in price_rows]
    cmd("simPriceFiniteRatioMin", fixed(_fmin(fin_ratio), 0))
    cmd("simPriceFiniteRatioMax", fixed(_fmax(fin_ratio), 0))
    over = [r.lo / r.dl_p.mean for r in price_rows]
    cmd("simPriceOverMin", fixed(_fmin(over), 0))
    cmd("simPriceOverMax", fixed(_fmax(over), 0))
    cap_ok = all(r.dl_p.mean <= r.live1 - r.l_p for r in price_rows)
    cmd("simPriceCapHolds", "every" if cap_ok else "not every")
    fin = checks.finite_source_scenario()
    cmd("simFiniteRatioMax", fixed(fin[0].wait_open / fin[0].wait_exact, 1))
    cmd("simFiniteRatioMin", fixed(fin[-1].wait_open / fin[-1].wait_exact, 2))
    cmd("simFiniteNMin", fin[0].n)
    cmd("simFiniteNMax", fin[-1].n)
    cmd("simFiniteRho", disp(checks.FINITE_SOURCE_RHO))
    return "\n".join(m) + "\n"


def main(argv: list[str]) -> int:
    out = Path(argv[0]) if argv else REPO / "paper" / "sim"
    out.mkdir(parents=True, exist_ok=True)

    def write(name, body):
        (out / name).write_text(body)

    all_checks = checks.all_checks()
    data = Data()
    write("tab-inmodel.tex", in_model())
    write("tab-closed.tex", closed())
    write("tab-kingman.tex", kingman())
    t, ok, cells = offload()
    write("tab-offload.tex", t)
    write("tab-evict.tex", evict_offline(data))
    open_rows = seq_open.eviction_open_scenario()
    write("tab-evict-dyn.tex", evict_open(open_rows, data))
    write("tab-admission.tex", admission_table(open_rows, data))
    write("tab-ps.tex", ps_table())
    write("tab-footprint.tex", footprint_table())
    write("tab-lps.tex", lps_table(data))
    write("tab-inversion.tex", inversion_table(data))
    write("tab-finite.tex", finite_source_table(data))
    price_rows = [
        seq_replay.trace_price_row(rate, d) for rate in TRACE_RATES for d in TRACE_PRICE_DELTAS
    ]
    write("tab-trace-price.tex", trace_price_table(price_rows, data))
    write("tab-trace-split.tex", trace_split_table())
    write("tab-pd.tex", pd_latency())
    trace_rows = seq_replay.trace_replay_scenario()
    write("tab-trace.tex", trace_table(trace_rows, data))
    write("tab-pd-inmodel.tex", pd_in_model())
    write("macros.tex", macros(all_checks, open_rows, trace_rows, price_rows, ok, cells))
    (out / "data").mkdir(exist_ok=True)
    for name, body in data.files:
        (out / "data" / name).write_text(body)
    print(f"wrote {out} ({len(data.files)} data files)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
