//! Generate the LaTeX tables and macros of the paper's simulation section.
//!
//! ```text
//! cargo run --release --example paper_tables            # writes ../paper/sim/
//! cargo run --release --example paper_tables -- <dir>   # writes <dir>
//! ```
//!
//! Every number in `paper/simulation.tex` comes from these files, so the
//! paper cannot drift from the code. Scenarios and seeds are the ones in
//! `src/validation.rs`; `scripts/check_sim.sh` regenerates the files and
//! fails if the committed copies differ.

use std::fmt::Write as _;
use std::path::PathBuf;

use libqueuingsim::Dist;
use libqueuingsim::analytic::*;
use libqueuingsim::models::agentic::{
    self, AgenticConfig, EvictionPolicy, FetchMode, OffloadPolicy,
};
use libqueuingsim::models::batch::Phi;
use libqueuingsim::models::eviction::{self, ResumeModel};
use libqueuingsim::models::pd::{self, Load, Mode, PdConfig};
use libqueuingsim::models::queue::{self, QueueConfig};
use libqueuingsim::stats::Estimate;
use libqueuingsim::validation::{self, OpenEvictRow, offload_cfg, pd_cfg};

const HEADER: &str = "% Generated by `cargo run --release --example paper_tables` in\n\
                      % libqueuingsim/. Do not edit by hand.\n";

fn pm(e: Estimate, d: usize) -> String {
    format!("${:.d$} \\pm {:.d$}$", e.mean, e.half_width)
}

/// A table cell that can compete for "best in its group": the value as
/// displayed (rounded to the printed precision) and its rendering.
struct Cell {
    value: f64,
    text: String,
}

fn cell(value: f64, d: usize, text: String) -> Cell {
    let s = 10f64.powi(d as i32);
    Cell {
        value: (value * s).round() / s,
        text,
    }
}

/// Bold the rendering of every cell whose displayed value is the best of
/// the group (all tied cells are bold). Math cells (`$...$`) get
/// `\mathbf`, text cells `\textbf`.
fn bold_best(cells: &mut [Cell], lower_is_better: bool) {
    let best = cells.iter().map(|c| c.value).fold(
        if lower_is_better {
            f64::INFINITY
        } else {
            f64::NEG_INFINITY
        },
        |a, b| {
            if lower_is_better { a.min(b) } else { a.max(b) }
        },
    );
    for c in cells.iter_mut().filter(|c| c.value == best) {
        c.text = if c.text.starts_with('$') && c.text.ends_with('$') {
            format!("$\\mathbf{{{}}}$", &c.text[1..c.text.len() - 1])
        } else {
            format!("\\textbf{{{}}}", c.text)
        };
    }
}

fn csv_line(fields: &[String]) -> String {
    fields.join(",")
}

/// Machine-readable copies of the table data, one per figure, written to
/// `data/` next to the tables. `scripts/plot_sim.py` reads them.
struct Data {
    files: Vec<(&'static str, String)>,
}

impl Data {
    fn push(&mut self, name: &'static str, header: &str, rows: &[String]) {
        let mut s = String::from(
            "# Generated by `cargo run --release --example paper_tables` in libqueuingsim/. \
             Synthetic workload; do not edit by hand.\n",
        );
        s.push_str(header);
        s.push('\n');
        for r in rows {
            s.push_str(r);
            s.push('\n');
        }
        self.files.push((name, s));
    }
}

fn table(caption: &str, label: &str, cols: &str, head: &str, rows: &[String]) -> String {
    table_sep(caption, label, cols, head, rows, "3pt")
}

/// `colsep` is the `\tabcolsep` of the tabular (`3pt` by default; `2pt`
/// for the wide tables that would otherwise exceed the column width).
fn table_sep(
    caption: &str,
    label: &str,
    cols: &str,
    head: &str,
    rows: &[String],
    colsep: &str,
) -> String {
    let mut s = String::from(HEADER);
    writeln!(s, "\\begin{{table}}[t]").unwrap();
    writeln!(s, "\\caption{{{caption}}}").unwrap();
    writeln!(s, "\\label{{{label}}}").unwrap();
    writeln!(
        s,
        "\\centering\\small\\setlength{{\\tabcolsep}}{{{colsep}}}"
    )
    .unwrap();
    writeln!(s, "\\begin{{tabular}}{{@{{}}{cols}@{{}}}}").unwrap();
    writeln!(s, "\\toprule\n{head} \\\\\n\\midrule").unwrap();
    for r in rows {
        writeln!(s, "{r} \\\\").unwrap();
    }
    writeln!(s, "\\bottomrule\n\\end{{tabular}}\n\\end{{table}}").unwrap();
    s
}

fn in_model() -> String {
    let mut rows = vec![];
    let r = queue::simulate(&QueueConfig::mg1(9.0, Dist::exp(0.1), 2_000_000, 12));
    rows.push(format!(
        "M/M/1 $W$, $\\lambda=9$ & \\S\\ref{{sec:intro}} & {:.3} & {}",
        mm1_wait(10.0, 9.0),
        pm(r.sojourn, 3)
    ));
    let b = Dist::discrete(vec![0.1, 0.1, 0.1, 3.7], vec![0.25; 4]);
    let r = queue::simulate(&QueueConfig::mg1(0.7, b.clone(), 2_000_000, 33));
    rows.push(format!(
        "PK $W_q$, workload B & Eq.~\\eqref{{eq:pk}} & {:.3} & {}",
        pk_wait(0.7, b.second_moment(), 0.7),
        pm(r.wait, 3)
    ));
    let wa = queue::simulate(&QueueConfig::mg1(
        0.6,
        Dist::Deterministic(1.0),
        1_000_000,
        40,
    ));
    let wb = queue::simulate(&QueueConfig::mg1(0.6, b, 1_000_000, 40));
    rows.push(format!(
        "$W_q^B/W_q^A$, $\\rho=0.6$ & \\S\\ref{{sec:congestion}} & 3.43 & {:.2}",
        wb.wait.mean / wa.wait.mean
    ));
    let d = Dist::HitMiss {
        p_hit: 0.8,
        hit: 0.05,
        miss: 0.5,
    };
    let r = queue::simulate(&QueueConfig::mg1(1.8, d, 1_000_000, 54));
    rows.push(format!(
        "$\\rho$ at $p=0.8$ & \\S\\ref{{sec:congestion}} & {:.3} & {:.3}",
        mixture_utilization(1.8, 0.8, 0.05, 0.5),
        r.utilization
    ));
    let d = Dist::HitMiss {
        p_hit: 0.96,
        hit: 0.05,
        miss: 5.0,
    };
    let lam = 0.5 / d.mean();
    let g = queue::simulate(&QueueConfig::mg1(lam, d.clone(), 4_000_000, 60)).wait;
    let m = queue::simulate(&QueueConfig::mg1(lam, Dist::exp(d.mean()), 4_000_000, 60)).wait;
    rows.push(format!(
        "$W_q$ / M/M/1, $\\mathrm{{CV}}^2{{=}}{:.1}$ & \\S\\ref{{sec:congestion}} & {:.2} & {:.2}",
        d.cv2(),
        (1.0 + d.cv2()) / 2.0,
        g.mean / m.mean
    ));
    let m = validation::miss_price_scenario(0.05);
    rows.push(format!(
        "$\\Delta L$, $\\delta=0.05$ & Prop.~\\ref{{prop:price}} & $[{:.2},{:.2}]$ & {}",
        m.lo,
        m.hi,
        pm(m.dl, 3)
    ));
    let worst = [(6, 20), (12, 200), (18, 60)]
        .into_iter()
        .enumerate()
        .flat_map(|(i, (n, c))| eviction::sweep(3000, n, c, ResumeModel::Uniform, 90 + i as u64))
        .map(|r| r.shortest_first)
        .fold(0.0, f64::max);
    rows.push(format!(
        "max SF/OPT & Prop.~\\ref{{prop:blind}} & $\\le 2$ & {worst:.3}"
    ));
    table(
        "Simulation under each proposition's assumptions (in-model). \
         M/M/1: $\\mu=10$. PK: $\\rho=0.7$. Cache: $\\lambda=1.8$. \
         $\\Delta L$ (the prefill queue as an M/G/1 FIFO server): rise in \
         the mean number in system when a fraction \
         $\\delta$ of turns changes from hit ($0.05$\\,s) to miss ($0.5$\\,s) at \
         hit rate $0.8$, $\\rho=0.6$, against the bracket \
         $[\\lambda\\delta\\Phi,\\ \\tfrac{1-\\rho}{1-\\rho'}\\lambda\\delta\\Phi]$. \
         SF/OPT: worst of 9000 instances with equal $p_i$. $\\pm$ is a \
         95\\,\\% batch-means half-width. Times in seconds.",
        "tab:sim-inmodel",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        &rows,
    )
}

fn closed() -> String {
    let mut rows = vec![];
    for n in [16, 32, 64, 96] {
        let r = agentic::simulate(&AgenticConfig::example(n, 6.0e5));
        rows.push(format!(
            "{n} & {:.2} & {:.2} & {:.2} & {:.2} & {:.1}",
            r.throughput,
            r.hit_rate,
            r.service.mean(),
            r.service.cv2(),
            100.0 * r.irtl_residual(n as f64)
        ));
    }
    table(
        "Closed agent programs sharing one replica with a 600k-token KV pool \
         (shortest-first eviction, no offload). The hit rate is not an input: \
         it results from memory pressure. Last column: residual of the \
         interactive response-time law, $|N-X(R+Z)|/N$.",
        "tab:sim-closed",
        "rccccc",
        "$N$ & $X$ (turn/s) & Hit rate & $\\E[S]$ (s) & $\\mathrm{CV}^2$ & IRTL (\\%)",
        &rows,
    )
}

fn kingman() -> String {
    let s = Dist::HitMiss {
        p_hit: 0.96,
        hit: 0.05,
        miss: 5.0,
    };
    let rho = 0.7;
    let lam = rho / s.mean();
    let pk = pk_wait(lam, s.second_moment(), rho);
    let mut rows = vec![];
    for (i, ca2) in [2.0, 4.0, 8.0].into_iter().enumerate() {
        let ia = Dist::hyperexp_balanced(1.0 / lam, ca2);
        let cfg = QueueConfig {
            interarrival: ia.clone(),
            service: s.clone(),
            servers: 1,
            customers: 4_000_000,
            warmup: 200_000,
            seed: 70 + i as u64,
        };
        let w = queue::simulate(&cfg).wait;
        rows.push(format!(
            "{ca2:.0} & {pk:.2} & {} & {:.2}",
            pm(w, 2),
            kingman_bound(lam, ia.variance(), s.variance(), rho)
        ));
    }
    table(
        "Bursty (hyperexponential) arrivals with the service law of \
         \\S\\ref{sec:congestion}, $\\rho=0.7$. $c_a^2$ is the interarrival \
         $\\mathrm{CV}^2$. Mean waits in seconds.",
        "tab:sim-kingman",
        "cccc",
        "$c_a^2$ & PK & Simulated $W_q$ & Kingman bound",
        &rows,
    )
}

fn offload() -> (String, usize, usize) {
    let mut rows = vec![];
    let (mut ok, mut total) = (0, 0);
    for bw in [5.0e3, 2.0e4, 1.0e5] {
        for n in [32, 64] {
            let run = |p| agentic::simulate(&offload_cfg(n, bw, p));
            let (nv, al, se, pr) = (
                run(OffloadPolicy::Never),
                run(OffloadPolicy::Always),
                run(OffloadPolicy::Selective),
                run(OffloadPolicy::Priced),
            );
            let mut async_cfg = offload_cfg(n, bw, OffloadPolicy::Always);
            async_cfg.fetch = FetchMode::Async;
            let al_async = agentic::simulate(&async_cfg);
            total += 1;
            if se.throughput >= 0.97 * nv.throughput.max(al.throughput) {
                ok += 1;
            }
            let mut pols: Vec<Cell> = [&nv, &al, &se, &pr]
                .iter()
                .map(|r| cell(r.throughput, 2, format!("{:.2}", r.throughput)))
                .collect();
            bold_best(&mut pols, false);
            rows.push(format!(
                "{:.0}k & {n} & {} & {} & {} & {} & {:.2} & {:.2} / {:.0}",
                bw / 1e3,
                pols[0].text,
                pols[1].text,
                pols[2].text,
                pols[3].text,
                al.stall_load,
                al_async.throughput,
                al_async.response.mean()
            ));
        }
    }
    let t = table(
        "Offloading with blocking fetches (the replica waits for the tier). \
         Throughput in turns/s by tier bandwidth (tokens/s), concurrency $N$ \
         and policy; the best of the four policies per row in bold. Priced: \
         selective with the price of a miss in place \
         of $\\Delta S(1+Q)$ (with blocking fetches both tests reduce to \
         transfer $<\\Delta S$). Stall: fraction of replica time spent waiting on \
         fetches under always-offload. Last column: always-offload when \
         fetches complete before the turn queues (asynchronous), as \
         throughput / mean turn response time in s (including the fetch).",
        "tab:sim-offload",
        "rrcccccc",
        "Tier & $N$ & Never & Always & Selective & Priced & Stall & Async",
        &rows,
    );
    (t, ok, total)
}

/// A cost ratio; ratios of 1000 or more in scientific notation.
fn ratio(x: f64, d: usize) -> String {
    if x < 1000.0 {
        format!("{x:.d$}")
    } else {
        let k = x.log10().floor();
        format!("${:.1}{{\\times}}10^{{{k:.0}}}$", x / 10f64.powf(k))
    }
}

/// A ratio for the CSV files: plain decimals, scientific past 10^4.
fn ratio_csv(x: f64) -> String {
    if x < 1.0e4 {
        format!("{x:.5}")
    } else {
        format!("{x:.4e}")
    }
}

type RatioOf = fn(&eviction::Ratios) -> f64;

const OFFLINE_POLICIES: [(&str, RatioOf); 3] = [
    ("SF", |r| r.shortest_first),
    ("Density", |r| r.density_first),
    ("Guarded", |r| r.guarded_density),
];

fn evict_offline(data: &mut Data) -> String {
    let mut rows = vec![];
    let mut sweeps = vec![];
    for (name, id, rm, seed) in [
        ("equal $p_i$", "equal_p", ResumeModel::Uniform, 5),
        (
            "$p_i\\sim U[0.05,1]$",
            "varied_p",
            ResumeModel::Varied { lo: 0.05 },
            99,
        ),
        (
            "$p_i$ falls with $c_i$",
            "p_falls_with_c",
            ResumeModel::ShorterResumes,
            7,
        ),
    ] {
        sweeps.push((name, id, eviction::sweep(3000, 12, 200, rm, seed)));
    }
    sweeps.push((
        "arbitrary $w_i$",
        "arbitrary_w",
        eviction::sweep_weighted(3000, 12, 200, 161),
    ));
    let mut summary = vec![];
    let mut samples = vec![];
    for (name, id, v) in sweeps {
        let mut means = vec![];
        let mut maxes = vec![];
        for (pol, f) in OFFLINE_POLICIES {
            let mean = v.iter().map(f).sum::<f64>() / v.len() as f64;
            let max = v.iter().map(f).fold(0.0, f64::max);
            // Compete on the value at the printed precision; ratios in
            // scientific notation never win, so their raw value is fine.
            means.push(cell(mean, 3, ratio(mean, 3)));
            maxes.push(cell(max, 2, ratio(max, 2)));
            summary.push(csv_line(&[
                id.to_string(),
                pol.to_string(),
                ratio_csv(mean),
                ratio_csv(max),
            ]));
        }
        bold_best(&mut means, true);
        bold_best(&mut maxes, true);
        let cells: Vec<String> = means
            .iter()
            .zip(&maxes)
            .map(|(m, x)| format!("{} / {}", m.text, x.text))
            .collect();
        rows.push(format!("{name} & {}", cells.join(" & ")));
        for (i, r) in v.iter().enumerate() {
            samples.push(csv_line(&[
                id.to_string(),
                i.to_string(),
                ratio_csv(r.shortest_first),
                ratio_csv(r.density_first),
                ratio_csv(r.guarded_density),
            ]));
        }
    }
    data.push(
        "evict-offline.csv",
        "regime,policy,mean_cost_over_opt,max_cost_over_opt",
        &summary,
    );
    data.push(
        "evict-offline-samples.csv",
        "regime,instance,sf,density,guarded",
        &samples,
    );
    table(
        "Offline eviction: cost relative to the exact optimum of \
         \\eqref{eq:evict-priced}, mean / max over 3000 random instances per row \
         (12 programs, $c_i\\in\\{1,\\dots,200\\}$, $\\Delta C$ a random \
         10--60\\,\\% of the total); the lowest mean and the lowest max per \
         row in bold. First three rows: costs $p_ic_i^2$. \
         Last row: weights $w_i$ log-uniform on $[10^{-4},10^5]$, independent \
         of $c_i$; shortest-first does not see $w_i$ there, and its ratio is \
         the price of ignoring the weights. Guarded: the guarded density greedy \
         of \\S\\ref{sec:evict}.",
        "tab:sim-evict",
        "lccc",
        "Costs & SF & Density & Guarded",
        &rows,
    )
}

fn ps_table() -> String {
    let mut rows = vec![];
    let ins = validation::insensitivity_scenario();
    for r in &ins {
        rows.push(format!(
            "PS, {} & \\S\\ref{{sec:batch}} & {:.3} & {}",
            r.name,
            r.ps_theory,
            pm(r.ps, 3)
        ));
    }
    for r in &ins {
        rows.push(format!(
            "FIFO, {} & Eq.~\\eqref{{eq:pk}} & {:.3} & {}",
            r.name,
            r.fifo_theory,
            pm(r.fifo, 3)
        ));
    }
    for r in validation::bcmp_scenario() {
        let phi = match r.phi {
            Phi::Constant(c) => format!("$\\phi\\equiv{c}$"),
            Phi::Saturating { beta, .. } => format!("sat.\\ $\\phi$ ($\\beta{{=}}{beta}$)"),
        };
        rows.push(format!(
            "Loop, {phi} & \\S\\ref{{sec:sessions}} & {:.2} & {}",
            r.theory,
            pm(r.sim, 2)
        ));
    }
    let m = validation::ps_price_scenario(0.05);
    rows.push(format!(
        "PS $\\Delta L$, $\\delta{{=}}0.05$ & Prop.~\\ref{{prop:decode}} & $[{:.2},{:.2}]$ & {}",
        m.lo,
        m.hi,
        pm(m.dl, 3)
    ));
    let t = validation::two_stage_price_scenario(0.05);
    rows.push(format!(
        "2-stage $\\Delta L_P$, $\\delta{{=}}0.05$ & Prop.~\\ref{{prop:price}} & $[{:.2},{:.2}]$ & {}",
        t.lo,
        t.hi,
        pm(t.dl_p, 3)
    ));
    rows.push(format!(
        "2-stage $\\Delta L_D$, $\\delta{{=}}0.05$ & Prop.~\\ref{{prop:decode}} & 0 & {}",
        pm(t.dl_d, 3)
    ));
    table(
        &format!(
            "Batching server under its assumptions (in-model): mean number of \
         turns at the replica, $L=\\lambda R$. Rows 1--4: Poisson turns at \
         $\\rho=0.7$, work deterministic or hit/miss ($0.05$\\,s w.p.\\ $0.8$, \
         else $0.5$\\,s; both mean $0.14$\\,s); PS theory $\\rho/(1-\\rho)$, \
         FIFO theory $\\lambda W_q+\\rho$. Rows 5--6: sessions arrive Poisson, \
         each turn is followed by a tool call (mean 2\\,s, $\\mathrm{{CV}}^2=4$) \
         and another turn w.p.\\ $0.8$; theory $\\sum_n n\\pi(n)$ at \
         $\\lambda=\\Lambda/(1-p)$ ($\\rho=0.7$ for $\\phi\\equiv 1$, $\\rho=3$ \
         for $\\phi(n)=n/(1+\\beta(n-1))$). Row 7: rise of $L$ at a PS \
         server when a fraction $\\delta$ of turns becomes misses, hit rate \
         $0.8$, $\\rho=0.6$, against $[\\lambda\\delta\\Phi_{{\\mathrm{{PS}}}},\\ \
         \\tfrac{{C-\\rho}}{{C-\\rho'}}\\lambda\\delta\\Phi_{{\\mathrm{{PS}}}}]$. \
         Rows 8--9: the same misses on the two-resource replica (prefill \
         FIFO in the compute left by a decode batch of $0.1$\\,s per turn, \
         mean availability $\\bar r={:.2}$): rise of the number in the \
         prefill stage $L_P=\\lambda\\,\\mathrm{{TTFT}}$ against the FIFO \
         bracket at service $P/\\bar r$, and of the number in the decode \
         stage $L_D$, whose demand does not depend on hit or miss. $\\pm$ is \
         a 95\\,\\% batch-means half-width.",
            t.avail
        ),
        "tab:sim-ps",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        &rows,
    )
}

fn footprint_table() -> String {
    let rows: Vec<String> = validation::footprint_scenario()
        .iter()
        .map(|r| format!("{} & {:.4} & {}", r.law, r.theory, pm(r.sim, 4)))
        .collect();
    table(
        "Expected number of requests admitted in arrival order into $M=12$ \
         tokens of KV until the first that does not fit \
         (\\S\\ref{sec:batch}). Footprints $K$ i.i.d.; the two laws in \
         each pair have the same mean. Simulated: $10^6$ draws, $\\pm$ a \
         95\\,\\% half-width.",
        "tab:sim-footprint",
        "lcc",
        "Footprint & Theory & Simulated",
        &rows,
    )
}

fn lps_table(data: &mut Data) -> String {
    let scenario = validation::lps_scenario();
    let rows: Vec<String> = scenario
        .iter()
        .map(|r| {
            format!(
                "{} ({:.0}) & {:.1} & {:.2} & {} & {} & ${:+.0}$",
                r.service,
                r.cv2,
                r.u,
                r.theory,
                pm(r.ps, 2),
                pm(r.lps, 2),
                100.0 * (r.lps.mean / r.theory - 1.0)
            )
        })
        .collect();
    let csv: Vec<String> = scenario
        .iter()
        .map(|r| {
            csv_line(&[
                r.service.to_string(),
                format!("{:.1}", r.cv2),
                format!("{:.2}", r.u),
                format!("{:.4}", r.theory),
                format!("{:.4}", r.ps.mean),
                format!("{:.4}", r.ps.half_width),
                format!("{:.4}", r.lps.mean),
                format!("{:.4}", r.lps.half_width),
                format!("{:.3}", 100.0 * (r.lps.mean / r.theory - 1.0)),
                format!("{:.3}", 100.0 * r.lps.half_width / r.theory),
            ])
        })
        .collect();
    data.push(
        "lps.csv",
        "work,cv2,u,formula,ps,ps_hw,lps,lps_hw,err_pct,err_pct_hw",
        &csv,
    );
    table(
        &format!(
            "Batch cap $B={}$: exact limited PS (at most $B$ turns share \
             $\\phi(n)=n/(1+{}(n-1))$, FIFO beyond) against PS with $\\phi$ \
             flattened at $B$, the model's approximation. Poisson turns, work of \
             mean 1 with the given law ($\\mathrm{{CV}}^2$ in brackets), load \
             $u=\\rho/\\phi(B)$. Mean number at the replica; last column: \
             relative error of the approximation for LPS, in \\%. Mean \
             response time has the same relative error (Little).",
            validation::LPS_CAP,
            validation::LPS_BETA
        ),
        "tab:sim-lps",
        "lccccc",
        "Work & $u$ & Formula & PS & LPS & Err.",
        &rows,
    )
}

fn policy_name(p: EvictionPolicy) -> &'static str {
    match p {
        EvictionPolicy::ShortestFirst => "SF",
        EvictionPolicy::Lru => "LRU",
        EvictionPolicy::Density => "Density",
        EvictionPolicy::Priced => "Priced",
        EvictionPolicy::PricedMemory => "Priced/$\\tau$",
        EvictionPolicy::PricedMemoryBlocks => "Blocks",
        _ => unreachable!("not in the scenario"),
    }
}

const OPEN_WORKLOAD: &str = "Sessions arrive Poisson at rate $\\Lambda$ (per s): half agents \
     ($p_i=0.95$, 4--8k initial tokens, tool calls Exp(6\\,s)), half one-shot \
     documents ($p_i=0.3$, 15--30k tokens, think time Exp(2\\,s)); 600k-token \
     KV, batch cap 8";

/// ASCII policy id for the data files.
fn policy_id(p: EvictionPolicy) -> &'static str {
    match p {
        EvictionPolicy::ShortestFirst => "SF",
        EvictionPolicy::Lru => "LRU",
        EvictionPolicy::Density => "Density",
        EvictionPolicy::Priced => "Priced",
        EvictionPolicy::PricedMemory => "PricedTau",
        EvictionPolicy::PricedMemoryBlocks => "Blocks",
        _ => unreachable!("not in the scenario"),
    }
}

const OPEN_CSV_HEADER: &str = "rate,cap,policy,throughput,throughput_hw,hit,hit_hw,\
                               ttft,ttft_hw,ttft_p99,ttft_p99_hw,response,response_hw,\
                               entry_wait,entry_wait_hw,thrashed,seeds";

fn open_csv_line(r: &OpenEvictRow) -> String {
    let e = |e: Estimate| [format!("{:.4}", e.mean), format!("{:.4}", e.half_width)];
    let mut f = vec![
        format!("{:.2}", r.rate),
        r.cap.to_string(),
        policy_id(r.policy).to_string(),
    ];
    for est in [
        r.throughput,
        r.hit_rate,
        r.ttft,
        r.ttft_p99,
        r.response,
        r.entry_wait,
    ] {
        f.extend(e(est));
    }
    f.push(r.collapsed.to_string());
    f.push(validation::OPEN_SEEDS.to_string());
    csv_line(&f)
}

/// Rows of one (Λ, cap) group with the best value per metric in bold:
/// X (max), hit (max), TTFT (min, once with and once without its
/// half-width), p99 (min). `render` receives `[x, hit, ttft_pm, ttft, p99]`.
fn open_group_rows(
    group: &[&OpenEvictRow],
    render: impl Fn(&OpenEvictRow, [&str; 5]) -> String,
) -> Vec<String> {
    let col = |f: fn(&OpenEvictRow) -> Estimate, d: usize, with_hw: bool| -> Vec<Cell> {
        group
            .iter()
            .map(|r| {
                let e = f(r);
                let text = if with_hw {
                    pm(e, d)
                } else {
                    format!("{:.d$}", e.mean)
                };
                cell(e.mean, d, text)
            })
            .collect()
    };
    let mut x = col(|r| r.throughput, 2, false);
    let mut hit = col(|r| r.hit_rate, 2, false);
    let mut ttft_pm = col(|r| r.ttft, 2, true);
    let mut ttft = col(|r| r.ttft, 2, false);
    let mut p99 = col(|r| r.ttft_p99, 1, false);
    bold_best(&mut x, false);
    bold_best(&mut hit, false);
    bold_best(&mut ttft_pm, true);
    bold_best(&mut ttft, true);
    bold_best(&mut p99, true);
    group
        .iter()
        .enumerate()
        .map(|(i, r)| {
            render(
                r,
                [
                    &x[i].text,
                    &hit[i].text,
                    &ttft_pm[i].text,
                    &ttft[i].text,
                    &p99[i].text,
                ],
            )
        })
        .collect()
}

fn evict_open(open: &[OpenEvictRow], data: &mut Data) -> String {
    let mut rows = vec![];
    let mut csv = vec![];
    for rate in validation::OPEN_RATES {
        let group: Vec<&OpenEvictRow> = open
            .iter()
            .filter(|r| r.cap == validation::OPEN_CAP && r.rate == rate)
            .collect();
        rows.extend(open_group_rows(&group, |r, [x, hit, ttft, _, p99]| {
            format!(
                "{:.2} & {} & {x} & {hit} & {ttft} & {p99} & {} & {}",
                r.rate,
                policy_name(r.policy),
                pm(r.response, 2),
                r.collapsed
            )
        }));
        csv.extend(group.iter().map(|r| open_csv_line(r)));
    }
    data.push("evict-dyn.csv", OPEN_CSV_HEADER, &csv);
    table_sep(
        &format!(
            "Eviction with open sessions on the two-resource replica (decode \
             PS on bandwidth, prefill FIFO in the leftover compute). \
             {OPEN_WORKLOAD}, at most {} live sessions. Throughput (turns/s), \
             follow-up hit rate, mean and p99 time to first token (s), mean turn \
             response (s), and the number of the {} seeds that thrashed (hit \
             rate below $0.5$); $\\pm$ is a 95\\,\\% half-width over seeds; \
             the best throughput, hit rate, TTFT and p99 per load in bold. \
             Priced: $p_i\\Phi_i/c_i$ with the FIFO price of \
             Prop.~\\ref{{prop:price}} from online estimates of the prefill \
             queue; Priced/$\\tau$: per byte-second, $p_i\\Phi_i/(c_i\\tau_i)$ \
             (the threshold rule of \\S\\ref{{sec:evict}}); Blocks: the same price \
             on 512-token tail blocks, a partial miss re-prefilling only the \
             evicted suffix. The priced rules take $p_i$ and $\\tau_i$ from the \
             generating class (an oracle); the fixed keys see neither.",
            validation::OPEN_CAP,
            validation::OPEN_SEEDS
        ),
        "tab:sim-evict-dyn",
        "clcccccc",
        "$\\Lambda$ & Policy & $X$ & Hit & TTFT & p99 & $R$ & Thr.",
        &rows,
        "2pt",
    )
}

fn admission_table(open: &[OpenEvictRow], data: &mut Data) -> String {
    let mut rows = vec![];
    let mut csv = vec![];
    for cap in validation::OPEN_CAPS {
        for rate in validation::OPEN_RATES {
            let group: Vec<&OpenEvictRow> = validation::SWEEP_POLICIES
                .iter()
                .map(|&pol| {
                    open.iter()
                        .find(|r| r.cap == cap && r.rate == rate && r.policy == pol)
                        .expect("cell in scenario")
                })
                .collect();
            // TTFT shows the mean only (the table is at column width); the
            // half-width is in the data file and the figure.
            rows.extend(open_group_rows(&group, |r, [x, hit, _, ttft, p99]| {
                format!(
                    "{:.2} & {cap} & {} & {x} & {hit} & {ttft} & {p99} & {:.2} & {:.1} & {}",
                    r.rate,
                    policy_name(r.policy),
                    r.response.mean,
                    r.entry_wait.mean,
                    r.collapsed
                )
            }));
            csv.extend(group.iter().map(|r| open_csv_line(r)));
        }
    }
    data.push("admission.csv", OPEN_CSV_HEADER, &csv);
    table_sep(
        &format!(
            "Admission-cap sweep on the two-resource replica: the scenario of \
             Table~\\ref{{tab:sim-evict-dyn}} with at most 16, 24 or 32 live \
             sessions; later arrivals wait in an entry queue. Throughput \
             (turns/s), follow-up hit rate, mean and p99 time to first token \
             (s), mean turn response (s), mean entry-queue wait of a new \
             session (s), and the number of the {} seeds that thrashed. Means \
             over seeds; the best throughput, hit rate, TTFT and p99 per \
             ($\\Lambda$, cap) in bold. The 95\\,\\% half-widths over seeds \
             are the whiskers of the accompanying figure; \
             Table~\\ref{{tab:sim-evict-dyn}} states them for the rows it \
             shares. An entry wait of hundreds of \
             seconds means the replica does not carry the offered turn rate \
             and the entry queue grows over the run; such values depend on \
             the horizon (20\\,000\\,s).",
            validation::OPEN_SEEDS
        ),
        "tab:sim-admission",
        "ccl@{\\hspace{3pt}}cccccccc",
        "$\\Lambda$ & Cap & Policy & $X$ & Hit & TTFT & p99 & $R$ & Entry & Thr.",
        &rows,
        "2pt",
    )
}

const INVERSION_CSV_HEADER: &str = "bandwidth,move_over_service,rho_star,inversion_rate,hot_utilization,link_utilization,affinity,always_move,lookahead";

/// §3.2 / Prop. routing beyond its model: the load at which always moving
/// (fetching the state over a shared link) beats strict affinity, by link
/// bandwidth, against `ρ*` of Prop. routing (i).
fn inversion_table(data: &mut Data) -> String {
    let rows_all = validation::inversion_scenario();
    let mut rows = vec![];
    let mut csv = vec![];
    for r in &rows_all {
        let f = |o: Option<f64>, d: usize| o.map_or("--".to_string(), |v| format!("{v:.d$}"));
        rows.push(format!(
            "{:.0}k & {:.2} & {:.2} & {} & {} & {} & {} & {} & {}",
            r.bandwidth / 1e3,
            r.move_over_service,
            r.rho_star,
            f(r.inversion_rate, 2),
            f(r.hot_utilization, 2),
            f(r.link_utilization, 2),
            f(r.affinity_response, 3),
            f(r.move_response, 3),
            f(r.lookahead_response, 3)
        ));
        csv.push(format!(
            "{},{},{},{},{},{},{},{},{}",
            r.bandwidth,
            r.move_over_service,
            r.rho_star,
            r.inversion_rate.unwrap_or(f64::NAN),
            r.hot_utilization.unwrap_or(f64::NAN),
            r.link_utilization.unwrap_or(f64::NAN),
            r.affinity_response.unwrap_or(f64::NAN),
            r.move_response.unwrap_or(f64::NAN),
            r.lookahead_response.unwrap_or(f64::NAN)
        ));
    }
    data.push("inversion.csv", INVERSION_CSV_HEADER, &csv);
    table_sep(
        "Placement over 4 replicas with half of the new programs placed on \
         replica~0 (the affinity node), follow-up turns of 5--15k-token contexts, \
         state moved over one shared link of bandwidth $B$ (tokens/s) when that is \
         cheaper than recomputing it. $x$: mean move cost over mean service; \
         $\\rho^*=x/(1+x)$, the inversion utilisation of Eq.~\\eqref{eq:rhostar} \
         for one node and an idle alternative; Inv.: the lowest program rate (per s, \
         swept in steps of 0.05) at which always moving to the least-loaded replica \
         beats affinity in mean turn response beyond both confidence intervals; \
         $\\rho_0$: utilisation of the affinity node at that rate; $\\rho_L$: \
         utilisation of the shared link under always-move there; mean turn response \
         (s) of affinity, always-move and the lookahead rule of \
         Eq.~\\eqref{eq:lookahead}. The idle alternative gives the earliest \
         inversion, so $\\rho^*$ is a lower bound for any real alternative.",
        "tab:sim-inversion",
        "ccccccccc",
        "$B$ & $x$ & $\\rho^*$ & Inv. & $\\rho_0$ & $\\rho_L$ & Affinity & Move & Lookahead",
        &rows,
        "2pt",
    )
}

fn pd_in_model() -> String {
    let mut rows = vec![];
    let agg = pd::simulate(&pd_cfg(
        32,
        Mode::Aggregated,
        1.0,
        1.0,
        0.5,
        (2.0, 1.0),
        1000.0,
    ));
    rows.push(format!(
        "$\\mu_A$, $I=0.5$ & Prop.~\\ref{{prop:pd}} & {:.2} & {:.2}",
        agg_capacity_i(32.0, 1.0, 1.0, 0.5),
        agg.throughput
    ));
    let cfg = pd_cfg(
        32,
        Mode::Disaggregated {
            prefill_devices: 11,
        },
        1.0,
        1.0,
        0.5,
        (2.0, 1.0),
        1000.0,
    );
    let r = pd::simulate(&cfg);
    rows.push(format!(
        "$\\mu_{{PD}}$, $N_P=11$ & Prop.~\\ref{{prop:pd}} & {:.2} & {:.2}",
        pd::split_capacity(&cfg, 11),
        r.throughput
    ));
    table(
        "Scalar PD capacities under the assumptions of \
         Prop.~\\ref{prop:pd} (in-model): $N=32$, $s_P=s_D=1$, $g_P=2$. \
         Capacities in requests per second.",
        "tab:sim-pd-inmodel",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        &rows,
    )
}

fn pd_latency() -> String {
    let mut rows = vec![];
    for rate in [1.0, 1.6, 1.9] {
        let mut a = PdConfig::from_means(
            8,
            Mode::Aggregated,
            Load::Poisson { rate },
            1.0,
            3.0,
            0.0,
            (1.0, 1.0),
            f64::INFINITY,
            1.0,
        );
        a.requests = 100_000;
        a.warmup = 10_000;
        let mut d = a.clone();
        d.mode = Mode::Disaggregated { prefill_devices: 2 };
        rows.push(format!(
            "{rate:.1} & {} & {}",
            pm(pd::simulate(&a).latency, 2),
            pm(pd::simulate(&d).latency, 2)
        ));
    }
    table(
        "Latency at equal capacity: $N=8$, $s_P=1$, $s_D=3$, no gains or \
         interference, rate-matched split $N_P=2$. Both configurations have \
         capacity 2 requests/s. Mean end-to-end latency (s).",
        "tab:sim-pd",
        "ccc",
        "$\\lambda$ & Aggregated & PD ($N_P=2$)",
        &rows,
    )
}

const TRACE_CSV_HEADER: &str = "rate,pool,cap,hit,hit_hw,sessions,entry_wait,rho,cv2,mixture_share,\
                                mixture_share_hw,wait,pk_wait,ttft,ttft_hw,ttft_p99,prefill_number,seeds";

/// §4.1: the two-resource replica fed by replayed production sessions.
fn trace_table(rows_all: &[validation::TraceRow], data: &mut Data) -> String {
    let corpus = libqueuingsim::workload::TraceCorpus::weka();
    let mut rows = vec![];
    let mut csv = vec![];
    for r in rows_all {
        let pool = if r.kv.is_finite() {
            format!("{:.0}M", r.kv / 1e6)
        } else {
            "$\\infty$".to_string()
        };
        let regime = if r.kv.is_finite() {
            format!("closed $N{{=}}{}$", r.cap)
        } else {
            format!("open $\\Lambda{{=}}{:.3}$", r.rate)
        };
        rows.push(format!(
            "{pool} & {regime} & {:.2} & {:.2} & {:.1} & {:.2} & {:.0} & {:.0} & {:.0}",
            r.hit_rate.mean,
            r.mixture_share.mean,
            r.cv2.mean,
            r.rho.mean,
            r.wait.mean,
            r.pk_wait.mean,
            r.ttft.mean
        ));
        csv.push(format!(
            "{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}",
            r.rate,
            r.kv,
            r.cap,
            r.hit_rate.mean,
            r.hit_rate.half_width,
            r.sessions.mean,
            r.entry_wait.mean,
            r.rho.mean,
            r.cv2.mean,
            r.mixture_share.mean,
            r.mixture_share.half_width,
            r.wait.mean,
            r.pk_wait.mean,
            r.ttft.mean,
            r.ttft.half_width,
            r.ttft_p99.mean,
            r.prefill_number.mean,
            validation::TRACE_SEEDS
        ));
    }
    data.push("trace.csv", TRACE_CSV_HEADER, &csv);
    table_sep(
        &format!(
            "Replayed production sessions on the two-resource replica: {} Claude Code \
             sessions ({} turns, mean final context {:.0}k tokens, mean think time \
             {:.0}\\,s; a gap above 10\\,min starts a new session) from the corpus of \
             \\S\\ref{{sec:exp-traces}}, each played turn by turn; cost model with \
             $K_c=a/b=50$k tokens, batch cap 8, eviction by price per byte-second. \
             With no pool limit the replica is open (Poisson sessions at rate \
             $\\Lambda$ per s, at most 24 live). With a finite pool the cap on live \
             sessions binds throughout the run, so the replica is a closed system of \
             $N$ sessions and the arrival rate is immaterial; the entry queue grows \
             for the whole horizon (waits in the data file). Follow-up hit rate; \
             the share of $\\mathrm{{Var}}[S]$ of follow-up prefill work due to the \
             hit/miss mixture (the rest is the spread of the appends) and the \
             $\\mathrm{{CV}}^2$ of that work; prefill load $\\rho$ in stage time; observed \
             mean prefill wait $W_q$ and the PK wait from the measured $\\lambda$, \
             $\\E[S]$, $\\E[S^2]$ (s); mean TTFT (s). Means over {} seeds; the \
             half-widths are in the data file.",
            corpus.sessions.len(),
            corpus.turns(),
            corpus.mean_final_context() / 1e3,
            corpus.mean_think(),
            validation::TRACE_SEEDS
        ),
        "tab:sim-trace",
        "clccccccc",
        "Pool & Regime & Hit & Mix & $\\mathrm{{CV}}^2$ & $\\rho$ & $W_q$ & PK & TTFT",
        &rows,
        "2pt",
    )
}

fn main() {
    let dir = std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("../paper/sim"));
    std::fs::create_dir_all(&dir).expect("create output dir");
    let write = |name: &str, body: &str| {
        std::fs::write(dir.join(name), body).expect("write table");
    };

    let checks = validation::all();
    let passed = checks.iter().filter(|c| c.pass).count();
    let pd_check = checks
        .iter()
        .find(|c| c.id == "pd_win_condition_decisions")
        .expect("pd check");
    let (agree, total) = pd_check
        .observed
        .split_whitespace()
        .next()
        .and_then(|s| s.split_once('/'))
        .expect("'a/b agree' prefix");

    let mut data = Data { files: vec![] };
    write("tab-inmodel.tex", &in_model());
    write("tab-closed.tex", &closed());
    write("tab-kingman.tex", &kingman());
    let (t, ok, cells) = offload();
    write("tab-offload.tex", &t);
    write("tab-evict.tex", &evict_offline(&mut data));
    let open = validation::eviction_open_scenario();
    write("tab-evict-dyn.tex", &evict_open(&open, &mut data));
    write("tab-admission.tex", &admission_table(&open, &mut data));
    write("tab-ps.tex", &ps_table());
    write("tab-footprint.tex", &footprint_table());
    write("tab-lps.tex", &lps_table(&mut data));
    write("tab-inversion.tex", &inversion_table(&mut data));
    write("tab-pd.tex", &pd_latency());
    let trace_rows = validation::trace_replay_scenario();
    write("tab-trace.tex", &trace_table(&trace_rows, &mut data));
    write("tab-pd-inmodel.tex", &pd_in_model());

    let mut m = String::from(HEADER);
    writeln!(m, "\\newcommand{{\\simChecks}}{{{}}}", checks.len()).unwrap();
    writeln!(m, "\\newcommand{{\\simChecksPassed}}{{{passed}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simPdAgree}}{{{agree}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simPdCells}}{{{total}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simOffloadOk}}{{{ok}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simOffloadCells}}{{{cells}}}").unwrap();
    // Trace replay: ranges over cells (PK/W_q ratio; hit rate and mixture
    // share at the tight cap; TTFT of the uncapped infinite pool).
    let corpus = libqueuingsim::workload::TraceCorpus::weka();
    let ratio: Vec<f64> = trace_rows
        .iter()
        .map(|r| r.pk_wait.mean / r.wait.mean)
        .collect();
    let tight: Vec<&validation::TraceRow> = trace_rows
        .iter()
        .filter(|r| {
            r.kv.is_finite()
                && r.cap == validation::trace_cap(&corpus, r.kv, validation::TRACE_CAP_FACTORS[0])
        })
        .collect();
    let loose: Vec<&validation::TraceRow> = trace_rows
        .iter()
        .filter(|r| {
            r.kv.is_finite()
                && r.cap == validation::trace_cap(&corpus, r.kv, validation::TRACE_CAP_FACTORS[1])
        })
        .collect();
    let open: Vec<&validation::TraceRow> =
        trace_rows.iter().filter(|r| !r.kv.is_finite()).collect();
    let fmin = |xs: &[f64]| xs.iter().cloned().fold(f64::INFINITY, f64::min);
    let fmax = |xs: &[f64]| xs.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    writeln!(
        m,
        "\\newcommand{{\\simTracePkRatioMin}}{{{:.0}}}",
        fmin(&ratio)
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTracePkRatioMax}}{{{:.0}}}",
        fmax(&ratio)
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceOpenCvMin}}{{{:.0}}}",
        fmin(&open.iter().map(|r| r.cv2.mean).collect::<Vec<_>>())
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceOpenCvMax}}{{{:.0}}}",
        fmax(&open.iter().map(|r| r.cv2.mean).collect::<Vec<_>>())
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceOpenTtftMin}}{{{:.0}}}",
        fmin(&open.iter().map(|r| r.ttft.mean).collect::<Vec<_>>())
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceOpenTtftMax}}{{{:.0}}}",
        fmax(&open.iter().map(|r| r.ttft.mean).collect::<Vec<_>>())
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceTightHitMin}}{{{:.2}}}",
        fmin(&tight.iter().map(|r| r.hit_rate.mean).collect::<Vec<_>>())
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceTightMixMin}}{{{:.0}}}",
        100.0
            * fmin(
                &tight
                    .iter()
                    .map(|r| r.mixture_share.mean)
                    .collect::<Vec<_>>()
            )
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceTightMixMax}}{{{:.0}}}",
        100.0
            * fmax(
                &tight
                    .iter()
                    .map(|r| r.mixture_share.mean)
                    .collect::<Vec<_>>()
            )
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceLooseHitMax}}{{{:.2}}}",
        fmax(&loose.iter().map(|r| r.hit_rate.mean).collect::<Vec<_>>())
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceLooseTtftMin}}{{{:.0}}}",
        fmin(&loose.iter().map(|r| r.ttft.mean).collect::<Vec<_>>())
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceSessions}}{{{}}}",
        corpus.sessions.len()
    )
    .unwrap();
    writeln!(
        m,
        "\\newcommand{{\\simTraceEntryMaxHours}}{{{:.0}}}",
        fmax(
            &trace_rows
                .iter()
                .map(|r| r.entry_wait.mean / 3600.0)
                .collect::<Vec<_>>()
        )
    )
    .unwrap();
    write("macros.tex", &m);

    // Machine-readable data behind the figures (scripts/plot_sim.py).
    let data_dir = dir.join("data");
    std::fs::create_dir_all(&data_dir).expect("create data dir");
    for (name, body) in &data.files {
        std::fs::write(data_dir.join(name), body).expect("write data file");
    }
    eprintln!("wrote {} ({} data files)", dir.display(), data.files.len());
}
