//! Generate the LaTeX tables and macros of the paper's simulation section.
//!
//! ```text
//! cargo run --release --example paper_tables            # writes ../paper/sim/
//! cargo run --release --example paper_tables -- <dir>   # writes <dir>
//! ```
//!
//! Every number in `paper/simulation.tex` comes from these files, so the
//! paper cannot drift from the code. Scenarios and seeds are the ones in
//! `src/validation.rs`; `scripts/check_sim.sh` regenerates the files and
//! fails if the committed copies differ.

use std::fmt::Write as _;
use std::path::PathBuf;

use libqueuingsim::Dist;
use libqueuingsim::analytic::*;
use libqueuingsim::models::agentic::{
    self, AgenticConfig, EvictionPolicy, FetchMode, OffloadPolicy,
};
use libqueuingsim::models::eviction::{self, ResumeModel};
use libqueuingsim::models::pd::{self, Load, Mode, PdConfig};
use libqueuingsim::models::queue::{self, QueueConfig};
use libqueuingsim::models::routing::{self, RoutePolicy, RoutingConfig};
use libqueuingsim::stats::{Estimate, replications};
use libqueuingsim::validation::{self, mixed_workload, offload_cfg, pd_cfg};

const HEADER: &str = "% Generated by `cargo run --release --example paper_tables` in\n\
                      % libqueuingsim/. Do not edit by hand.\n";

fn pm(e: Estimate, d: usize) -> String {
    format!("${:.d$} \\pm {:.d$}$", e.mean, e.half_width)
}

fn table(caption: &str, label: &str, cols: &str, head: &str, rows: &[String]) -> String {
    let mut s = String::from(HEADER);
    writeln!(s, "\\begin{{table}}[t]").unwrap();
    writeln!(s, "\\caption{{{caption}}}").unwrap();
    writeln!(s, "\\label{{{label}}}").unwrap();
    writeln!(s, "\\centering\\small").unwrap();
    writeln!(s, "\\begin{{tabular}}{{@{{}}{cols}@{{}}}}").unwrap();
    writeln!(s, "\\toprule\n{head} \\\\\n\\midrule").unwrap();
    for r in rows {
        writeln!(s, "{r} \\\\").unwrap();
    }
    writeln!(s, "\\bottomrule\n\\end{{tabular}}\n\\end{{table}}").unwrap();
    s
}

fn in_model() -> String {
    let mut rows = vec![];
    let r = queue::simulate(&QueueConfig::mg1(9.0, Dist::exp(0.1), 2_000_000, 12));
    rows.push(format!(
        "M/M/1 $W$, $\\lambda=9$ & \\S\\ref{{sec:intro}} & {:.3} & {}",
        mm1_wait(10.0, 9.0),
        pm(r.sojourn, 3)
    ));
    let b = Dist::discrete(vec![0.1, 0.1, 0.1, 3.7], vec![0.25; 4]);
    let r = queue::simulate(&QueueConfig::mg1(0.7, b.clone(), 2_000_000, 33));
    rows.push(format!(
        "PK $W_q$, workload B & Thm.~\\ref{{thm:pk}} & {:.3} & {}",
        pk_wait(0.7, b.second_moment(), 0.7),
        pm(r.wait, 3)
    ));
    let wa = queue::simulate(&QueueConfig::mg1(
        0.6,
        Dist::Deterministic(1.0),
        1_000_000,
        40,
    ));
    let wb = queue::simulate(&QueueConfig::mg1(0.6, b, 1_000_000, 40));
    rows.push(format!(
        "$W_q^B/W_q^A$, $\\rho=0.6$ & Prop.~\\ref{{prop:pk}} & 3.43 & {:.2}",
        wb.wait.mean / wa.wait.mean
    ));
    let d = Dist::HitMiss {
        p_hit: 0.8,
        hit: 0.05,
        miss: 0.5,
    };
    let r = queue::simulate(&QueueConfig::mg1(1.8, d, 1_000_000, 54));
    rows.push(format!(
        "$\\rho$ at $p=0.8$ & Prop.~\\ref{{prop:cache}} & {:.3} & {:.3}",
        mixture_utilization(1.8, 0.8, 0.05, 0.5),
        r.utilization
    ));
    let d = Dist::HitMiss {
        p_hit: 0.96,
        hit: 0.05,
        miss: 5.0,
    };
    let lam = 0.5 / d.mean();
    let g = queue::simulate(&QueueConfig::mg1(lam, d.clone(), 4_000_000, 60)).wait;
    let m = queue::simulate(&QueueConfig::mg1(lam, Dist::exp(d.mean()), 4_000_000, 60)).wait;
    rows.push(format!(
        "$W_q$ / M/M/1, $\\mathrm{{CV}}^2{{=}}{:.1}$ & Eq.~\\eqref{{eq:cv2}} & {:.2} & {:.2}",
        d.cv2(),
        (1.0 + d.cv2()) / 2.0,
        g.mean / m.mean
    ));
    let worst = [(6, 20), (12, 200), (18, 60)]
        .into_iter()
        .enumerate()
        .flat_map(|(i, (n, c))| eviction::sweep(3000, n, c, ResumeModel::Uniform, 90 + i as u64))
        .map(|r| r.shortest_first)
        .fold(0.0, f64::max);
    rows.push(format!(
        "max SF/OPT & Prop.~\\ref{{prop:evict}} & $\\le 2$ & {worst:.3}"
    ));
    table(
        "Simulation under each proposition's assumptions (in-model). \
         M/M/1: $\\mu=10$. PK: $\\rho=0.7$. Cache: $\\lambda=1.8$. \
         SF/OPT: worst of 9000 instances with equal $p_i$. $\\pm$ is a \
         95\\,\\% batch-means half-width. Times in seconds.",
        "tab:sim-inmodel",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        &rows,
    )
}

fn closed() -> String {
    let mut rows = vec![];
    for n in [16, 32, 64, 96] {
        let r = agentic::simulate(&AgenticConfig::example(n, 6.0e5));
        rows.push(format!(
            "{n} & {:.2} & {:.2} & {:.2} & {:.2} & {:.1}",
            r.throughput,
            r.hit_rate,
            r.service.mean(),
            r.service.cv2(),
            100.0 * r.irtl_residual(n as f64)
        ));
    }
    table(
        "Closed agent programs sharing one replica with a 600k-token KV pool \
         (shortest-first eviction, no offload). The hit rate is not an input: \
         it results from memory pressure. Last column: residual of the \
         interactive response-time law, $|N-X(R+Z)|/N$.",
        "tab:sim-closed",
        "rccccc",
        "$N$ & $X$ (turn/s) & Hit rate & $\\E[S]$ (s) & $\\mathrm{CV}^2$ & IRTL (\\%)",
        &rows,
    )
}

fn kingman() -> String {
    let s = Dist::HitMiss {
        p_hit: 0.96,
        hit: 0.05,
        miss: 5.0,
    };
    let rho = 0.7;
    let lam = rho / s.mean();
    let pk = pk_wait(lam, s.second_moment(), rho);
    let mut rows = vec![];
    for (i, ca2) in [2.0, 4.0, 8.0].into_iter().enumerate() {
        let ia = Dist::hyperexp_balanced(1.0 / lam, ca2);
        let cfg = QueueConfig {
            interarrival: ia.clone(),
            service: s.clone(),
            servers: 1,
            customers: 4_000_000,
            warmup: 200_000,
            seed: 70 + i as u64,
        };
        let w = queue::simulate(&cfg).wait;
        rows.push(format!(
            "{ca2:.0} & {pk:.2} & {} & {:.2}",
            pm(w, 2),
            kingman_bound(lam, ia.variance(), s.variance(), rho)
        ));
    }
    table(
        "Bursty (hyperexponential) arrivals with the service law of \
         Eq.~\\eqref{eq:cv2}, $\\rho=0.7$. $c_a^2$ is the interarrival \
         $\\mathrm{CV}^2$. Mean waits in seconds.",
        "tab:sim-kingman",
        "cccc",
        "$c_a^2$ & PK & Simulated $W_q$ & Kingman bound",
        &rows,
    )
}

fn offload() -> (String, usize, usize) {
    let mut rows = vec![];
    let (mut ok, mut total) = (0, 0);
    for bw in [5.0e3, 2.0e4, 1.0e5] {
        for n in [32, 64] {
            let run = |p| agentic::simulate(&offload_cfg(n, bw, p));
            let (nv, al, se) = (
                run(OffloadPolicy::Never),
                run(OffloadPolicy::Always),
                run(OffloadPolicy::Selective),
            );
            let mut async_cfg = offload_cfg(n, bw, OffloadPolicy::Always);
            async_cfg.fetch = FetchMode::Async;
            let al_async = agentic::simulate(&async_cfg);
            total += 1;
            if se.throughput >= 0.97 * nv.throughput.max(al.throughput) {
                ok += 1;
            }
            rows.push(format!(
                "{:.0}k & {n} & {:.2} & {:.2} & {:.2} & {:.2} & {:.2} / {:.0}",
                bw / 1e3,
                nv.throughput,
                al.throughput,
                se.throughput,
                al.stall_load,
                al_async.throughput,
                al_async.response.mean()
            ));
        }
    }
    let t = table(
        "Offloading with blocking fetches (the replica waits for the tier). \
         Throughput in turns/s by tier bandwidth (tokens/s), concurrency $N$ \
         and policy. Stall: fraction of replica time spent waiting on \
         fetches under always-offload. Last column: always-offload when \
         fetches complete before the turn queues (asynchronous), as \
         throughput / mean turn response time in s (including the fetch).",
        "tab:sim-offload",
        "rrccccc",
        "Tier & $N$ & Never & Always & Selective & Stall & Async",
        &rows,
    );
    (t, ok, total)
}

fn evict_offline() -> String {
    let mut rows = vec![];
    for (name, rm, seed) in [
        ("equal $p_i$", ResumeModel::Uniform, 5),
        ("$p_i\\sim U[0.05,1]$", ResumeModel::Varied { lo: 0.05 }, 99),
        ("$p_i$ falls with $c_i$", ResumeModel::ShorterResumes, 7),
    ] {
        let v = eviction::sweep(3000, 12, 200, rm, seed);
        let stat = |f: fn(&eviction::Ratios) -> f64| {
            let mean = v.iter().map(f).sum::<f64>() / v.len() as f64;
            let max = v.iter().map(f).fold(0.0, f64::max);
            (mean, max)
        };
        let (sm, sx) = stat(|r| r.shortest_first);
        let (dm, dx) = stat(|r| r.density_first);
        rows.push(format!("{name} & {sm:.3} & {sx:.2} & {dm:.3} & {dx:.2}"));
    }
    table(
        "Offline eviction: cost relative to the exact optimum of \
         \\eqref{eq:evict} with costs $p_ic_i^2$, over 3000 random instances \
         per row (12 programs, $c_i\\in\\{1,\\dots,200\\}$, $\\Delta C$ a \
         random 10--60\\,\\% of the total).",
        "tab:sim-evict",
        "lcccc",
        "Resume model & \\multicolumn{2}{c}{SF mean / max} & \\multicolumn{2}{c}{Density mean / max}",
        &rows,
    )
}

fn evict_dynamic() -> String {
    let mut rows = vec![];
    for n in [16, 24, 32] {
        let mut cells = vec![n.to_string()];
        for ev in [
            EvictionPolicy::ShortestFirst,
            EvictionPolicy::Density,
            EvictionPolicy::Lru,
        ] {
            let xs: Vec<f64> = (1..=5)
                .map(|s| agentic::simulate(&mixed_workload(n, s, ev)).throughput)
                .collect();
            cells.push(pm(replications(&xs), 2));
        }
        rows.push(cells.join(" & "));
    }
    table(
        "Eviction inside the closed system: throughput (turns/s, mean and \
         95\\,\\% half-width over 5 seeds) for a two-class mix of agents \
         ($p_i=0.95$, 4--8k initial tokens) and one-shot long documents \
         ($p_i=0.2$, 30--60k tokens) on a 400k-token pool.",
        "tab:sim-evict-dyn",
        "rccc",
        "$N$ & Shortest-first & Density & LRU",
        &rows,
    )
}

fn routing_table() -> String {
    let mut rows = vec![];
    for rate in [0.6, 1.2, 1.6, 1.8] {
        let mut cells = vec![format!("{rate:.1}")];
        for pol in [
            RoutePolicy::Affinity,
            RoutePolicy::Myopic,
            RoutePolicy::Lookahead,
        ] {
            let r = routing::simulate(&RoutingConfig::example(rate, pol));
            cells.push(format!("{:.3} / {:.2}", r.response.mean, r.p99));
        }
        rows.push(cells.join(" & "));
    }
    table(
        "Routing follow-up turns over 4 replicas, half of new programs placed \
         on replica~0. Mean / p99 turn response time (s) by program arrival \
         rate (per s).",
        "tab:sim-routing",
        "cccc",
        "Rate & Affinity & KV-aware myopic & Lookahead",
        &rows,
    )
}

fn pd_in_model() -> String {
    let mut rows = vec![];
    let agg = pd::simulate(&pd_cfg(
        32,
        Mode::Aggregated,
        1.0,
        1.0,
        0.5,
        (2.0, 1.0),
        1000.0,
    ));
    rows.push(format!(
        "$\\mu_A$, $I=0.5$ & Prop.~\\ref{{prop:pd}} & {:.2} & {:.2}",
        agg_capacity_i(32.0, 1.0, 1.0, 0.5),
        agg.throughput
    ));
    let cfg = pd_cfg(
        32,
        Mode::Disaggregated {
            prefill_devices: 11,
        },
        1.0,
        1.0,
        0.5,
        (2.0, 1.0),
        1000.0,
    );
    let r = pd::simulate(&cfg);
    rows.push(format!(
        "$\\mu_{{PD}}$, $N_P=11$ & Prop.~\\ref{{prop:pd}} & {:.2} & {:.2}",
        pd::split_capacity(&cfg, 11),
        r.throughput
    ));
    table(
        "Scalar PD capacities under the assumptions of \
         Prop.~\\ref{prop:pd} (in-model): $N=32$, $s_P=s_D=1$, $g_P=2$. \
         Capacities in requests per second.",
        "tab:sim-pd-inmodel",
        "l@{\\hspace{4pt}}lcc",
        "Quantity & Result & Theory & Simulated",
        &rows,
    )
}

fn pd_latency() -> String {
    let mut rows = vec![];
    for rate in [1.0, 1.6, 1.9] {
        let mut a = PdConfig::from_means(
            8,
            Mode::Aggregated,
            Load::Poisson { rate },
            1.0,
            3.0,
            0.0,
            (1.0, 1.0),
            f64::INFINITY,
            1.0,
        );
        a.requests = 100_000;
        a.warmup = 10_000;
        let mut d = a.clone();
        d.mode = Mode::Disaggregated { prefill_devices: 2 };
        rows.push(format!(
            "{rate:.1} & {} & {}",
            pm(pd::simulate(&a).latency, 2),
            pm(pd::simulate(&d).latency, 2)
        ));
    }
    table(
        "Latency at equal capacity: $N=8$, $s_P=1$, $s_D=3$, no gains or \
         interference, rate-matched split $N_P=2$. Both configurations have \
         capacity 2 requests/s. Mean end-to-end latency (s).",
        "tab:sim-pd",
        "ccc",
        "$\\lambda$ & Aggregated & PD ($N_P=2$)",
        &rows,
    )
}

fn main() {
    let dir = std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("../paper/sim"));
    std::fs::create_dir_all(&dir).expect("create output dir");
    let write = |name: &str, body: &str| {
        std::fs::write(dir.join(name), body).expect("write table");
    };

    let checks = validation::all();
    let passed = checks.iter().filter(|c| c.pass).count();
    let pd_check = checks
        .iter()
        .find(|c| c.id == "pd_win_condition_decisions")
        .expect("pd check");
    let (agree, total) = pd_check
        .observed
        .split_whitespace()
        .next()
        .and_then(|s| s.split_once('/'))
        .expect("'a/b agree' prefix");

    write("tab-inmodel.tex", &in_model());
    write("tab-closed.tex", &closed());
    write("tab-kingman.tex", &kingman());
    let (t, ok, cells) = offload();
    write("tab-offload.tex", &t);
    write("tab-evict.tex", &evict_offline());
    write("tab-evict-dyn.tex", &evict_dynamic());
    write("tab-routing.tex", &routing_table());
    write("tab-pd.tex", &pd_latency());
    write("tab-pd-inmodel.tex", &pd_in_model());

    let mut m = String::from(HEADER);
    writeln!(m, "\\newcommand{{\\simChecks}}{{{}}}", checks.len()).unwrap();
    writeln!(m, "\\newcommand{{\\simChecksPassed}}{{{passed}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simPdAgree}}{{{agree}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simPdCells}}{{{total}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simOffloadOk}}{{{ok}}}").unwrap();
    writeln!(m, "\\newcommand{{\\simOffloadCells}}{{{cells}}}").unwrap();
    write("macros.tex", &m);
    eprintln!("wrote {}", dir.display());
}
