#!/usr/bin/env python3
"""E1: fit the prefill cost model to the probes of probe_prefill.py and write
the fit plus the paper table (generated; never type the numbers by hand).

  P(n, K) = c0 + a n + b n (K + n/2)      [seconds]

n = new tokens, K = cached prefix tokens. Cold probes give K = 0; append
probes are used only when cached_tokens confirms the prefix (>= 50 %).

Outputs (paths relative to the repo root):
  data/exp/e1/fit.json          {"c0","a","b","kc","mape","r2","n_probes", ...}
  paper/exp/tab-e1.tex          table of probes: n, K, measured TTFT (mean over
                                repeats, spread), fitted P(n,K), error
  paper/exp/macros-e1.tex       \\eOneA, \\eOneB, \\eOneKc, \\eOneMape, \\eOneRsq ...

  python3 scripts/exp/fit_e1.py data/exp/e1/probes.jsonl
"""
import argparse
import json
import os
import statistics as st
from collections import defaultdict


def solve3(X, y):
    XtX = [[sum(X[i][j] * X[i][k] for i in range(len(X))) for k in range(3)] for j in range(3)]
    Xty = [sum(X[i][j] * y[i] for i in range(len(X))) for j in range(3)]
    M = [XtX[j] + [Xty[j]] for j in range(3)]
    for c in range(3):
        p = max(range(c, 3), key=lambda r: abs(M[r][c]))
        M[c], M[p] = M[p], M[c]
        for r in range(3):
            if r != c:
                f = M[r][c] / M[c][c]
                M[r] = [M[r][k] - f * M[c][k] for k in range(4)]
    return [M[j][3] / M[j][j] for j in range(3)]


def load_points(path):
    pts = []
    for line in open(path):
        if not line.strip():
            continue
        r = json.loads(line)
        if r["kind"] == "cold":
            pts.append((r["n"], 0, r["ttft_s"]))
        elif r["kind"] == "append":
            c = r.get("cached_tokens")
            if c is not None and c < 0.5 * r["K"]:
                continue
            pts.append((r["n"], r["K"], r["ttft_s"]))
    return pts


def fit(pts):
    X = [[1.0, n, n * (K + n / 2)] for n, K, _ in pts]
    y = [t for _, _, t in pts]
    c0, a, b = solve3(X, y)
    pred = [c0 + a * n + b * n * (K + n / 2) for n, K, _ in pts]
    mape = st.fmean(abs(p - t) / t for p, t in zip(pred, y))
    ybar = st.fmean(y)
    r2 = 1 - sum((p - t) ** 2 for p, t in zip(pred, y)) / sum((t - ybar) ** 2 for t in y)
    return dict(c0=c0, a=a, b=b, kc=a / b if b else float("inf"), mape=mape, r2=r2, n_probes=len(pts))


def fmt_tok(n):
    return f"{n // 1024}k" if n % 1024 == 0 and n >= 1024 else str(n)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("probes")
    ap.add_argument("--fit-out", default="data/exp/e1/fit.json")
    ap.add_argument("--tex-dir", default="paper/exp")
    a = ap.parse_args()
    pts = load_points(a.probes)
    if len(pts) < 4:
        raise SystemExit(f"only {len(pts)} usable probes")
    f = fit(pts)
    # held-out check: fit on cold, predict append (the reuse regime is what E2 uses)
    cold = [p for p in pts if p[1] == 0]
    app = [p for p in pts if p[1] > 0]
    if len(cold) >= 4 and app:
        fc = fit(cold)
        pred = [fc["c0"] + fc["a"] * n + fc["b"] * n * (K + n / 2) for n, K, _ in app]
        f["mape_append_from_cold"] = st.fmean(abs(p - t) / t for p, (_, _, t) in zip(pred, app))
    os.makedirs(os.path.dirname(a.fit_out) or ".", exist_ok=True)
    json.dump(f, open(a.fit_out, "w"), indent=1)
    print("fit:", {k: (round(v, 6) if isinstance(v, float) else v) for k, v in f.items()})

    # table: one row per (K, n), mean and spread over repeats
    groups = defaultdict(list)
    for n, K, t in pts:
        groups[(K, n)].append(t)
    os.makedirs(a.tex_dir, exist_ok=True)
    rows = []
    for (K, n) in sorted(groups):
        ts = groups[(K, n)]
        m = st.fmean(ts)
        spread = (max(ts) - min(ts)) / 2 if len(ts) > 1 else 0.0
        p = f["c0"] + f["a"] * n + f["b"] * n * (K + n / 2)
        rows.append(f"{fmt_tok(K)} & {fmt_tok(n)} & {m:.2f} $\\pm$ {spread:.2f} & {p:.2f} & {100 * (p - m) / m:+.1f} \\\\")
    with open(os.path.join(a.tex_dir, "tab-e1.tex"), "w") as out:
        out.write("% generated by scripts/exp/fit_e1.py; do not edit\n")
        out.write("\\begin{table}[t]\\centering\\scriptsize\n")
        out.write("\\caption{E1 prefill probes on the testbed (single requests on an idle replica group): cached prefix $K$, new tokens $n$, measured TTFT (mean $\\pm$ half-range over "
                  "repeats) and the fitted cost model $P(n,K)=c_0+an+bn(K+n/2)$.}\\label{tab:e1}\n")
        out.write("\\begin{tabular}{rrrrr}\\toprule\n$K$ & $n$ & TTFT (s) & $P(n,K)$ (s) & error \\\\\\midrule\n")
        out.write("\n".join(rows) + "\n\\bottomrule\\end{tabular}\\end{table}\n")
    with open(os.path.join(a.tex_dir, "macros-e1.tex"), "w") as out:
        out.write("% generated by scripts/exp/fit_e1.py; do not edit\n")
        out.write(f"\\newcommand{{\\eOneCzero}}{{{f['c0']:.3f}}}\n")
        out.write(f"\\newcommand{{\\eOneA}}{{{f['a'] * 1e3:.3f}}}\n")  # ms per token
        out.write(f"\\newcommand{{\\eOneB}}{{{f['b'] * 1e9:.2f}}}\n")  # ns per token^2
        out.write(f"\\newcommand{{\\eOneKc}}{{{f['kc'] / 1000:.0f}}}\n")  # k tokens
        out.write(f"\\newcommand{{\\eOneMape}}{{{100 * f['mape']:.1f}}}\n")
        out.write(f"\\newcommand{{\\eOneRsq}}{{{f['r2']:.3f}}}\n")
        out.write(f"\\newcommand{{\\eOneProbes}}{{{f['n_probes']}}}\n")
        # derived numbers quoted in the prose (from the same probes)
        cold = {n: st.fmean(ts) for (K, n), ts in groups.items() if K == 0}
        if 32768 in cold and 65536 in cold:
            out.write(f"\\newcommand{{\\eOneRatioSixtyFour}}{{{cold[65536] / cold[32768]:.1f}}}\n")
        nmax = max(cold)
        out.write(f"\\newcommand{{\\eOneColdMaxTokens}}{{{nmax // 1024}}}\n")
        out.write(f"\\newcommand{{\\eOneColdMaxTtft}}{{{cold[nmax]:.0f}}}\n")
        out.write(f"\\newcommand{{\\eOneColdMaxLinear}}{{{f['c0'] + f['a'] * nmax:.0f}}}\n")
        if "mape_append_from_cold" in f:
            out.write(f"\\newcommand{{\\eOneMapeHeldout}}{{{100 * f['mape_append_from_cold']:.1f}}}\n")
    print("wrote", a.fit_out, a.tex_dir)


if __name__ == "__main__":
    main()
