#!/usr/bin/env python3
"""E2: turn the JSON written by analyze_e2.py --out into the paper's generated
table and macros (paper/exp/tab-e2.tex, paper/exp/macros-e2.tex). Never type
these numbers into the paper by hand.

  python3 scripts/exp/paper_e2_tables.py data/exp/e2/summary.json

One row per replay run: session spacing and live-session cap, the mean
number of live sessions N̄, follow-up hit rate, prefill utilisation ρ (from
the E1 cost model), prefill-work CV², the hit/miss mixture's share of
Var[S], measured TTFT (mean, p99), the observed queueing wait W_obs =
TTFT − P(n,K), and the two predictions: the open PK wait and the
Markovian finite-source wait with N = round(N̄).
"""
import argparse
import json
import os
import re


def cap_label(params, path):
    cap = params.get("cap")
    if cap is None:
        m = re.search(r"c(\d+)", os.path.basename(os.path.dirname(path)))
        cap = int(m.group(1)) if m else 0
    return "$\\infty$" if int(cap) == 0 else str(cap)


def spacing_label(params, path):
    sp = params.get("spacing_s")
    if sp is None:
        m = re.search(r"s(\d+)", os.path.basename(os.path.dirname(path)))
        sp = int(m.group(1)) if m else 0
    return f"{float(sp):g}"


def macro(name, value):
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("summary")
    ap.add_argument("--tex-dir", default="paper/exp")
    a = ap.parse_args()
    runs = json.load(open(a.summary))
    runs = [r for r in runs if r]
    runs.sort(key=lambda r: (-float(r["params"].get("spacing_s", 0) or 0), -(int(r["params"].get("cap", 0) or 0) or 10**9)))
    os.makedirs(a.tex_dir, exist_ok=True)
    lines = []
    for r in runs:
        ratio_pk = r["pk"] / r["w_obs"] if r["w_obs"] > 0 and r["pk"] != float("inf") else float("nan")
        ratio_fin = r["w_fin"] / r["w_obs"] if r["w_obs"] > 0 else float("nan")
        pk = "$\\infty$" if r["pk"] == float("inf") else f"{r['pk']:.1f}"
        rho_col = f"{r['rho_lo']:.2f}--{r['rho_hi']:.2f}" if "rho_lo" in r else f"{r['rho']:.2f}"
        wq = r.get("q_srv", float("nan"))
        wq_col = f"{wq:.1f}" if wq == wq else f"{r['w_obs']:.1f}"
        kv = r.get("kv_usage", float("nan"))
        kv_col = f"{100 * kv:.0f}" if kv == kv else "--"
        lines.append(
            f"{spacing_label(r['params'], r['path'])} & {cap_label(r['params'], r['path'])} & {r['n_bar']:.1f} & "
            f"{100 * r['hit']:.0f} & {kv_col} & {rho_col} & {r['cv2']:.1f} & {100 * r['share']:.0f} & "
            f"{r['ttft_hit']:.1f} & {r['ttft_miss']:.1f} & {r['ttft_p99']:.0f} & {wq_col} & {pk} & {r['w_fin']:.1f} \\\\"
        )
    with open(os.path.join(a.tex_dir, "tab-e2.tex"), "w") as out:
        out.write("% generated by scripts/exp/paper_e2_tables.py; do not edit\n")
        out.write("\\begin{table*}[t]\\centering\\scriptsize\n")
        out.write(
            "\\caption{E2: open-loop replay of the coding-agent trace on the testbed (four ranks, sessions pinned), one session every $s$ seconds, at most $N_{\\max}$ live. "
            "$\\bar N$: mean live sessions; hit: follow-up turns whose cached prefix covers their context; KV: mean pool occupancy; $\\rho$: per-rank prefill utilisation from the E1 cost model; "
            "mix: the hit/miss mixture's share of the variance of follow-up prefill work; $W_q$: the server's mean queueing time before the first prefill chunk; "
            "PK and finite: the open PK wait and the Markovian finite-source wait (Proposition~\\ref{prop:finite}) per rank, request-weighted.}"
            "\\label{tab:e2}\n"
        )
        out.write("\\begin{tabular}{rrrrrrrrrrrrrr}\\toprule\n")
        out.write("$s$ (s) & $N_{\\max}$ & $\\bar N$ & hit (\\%) & KV (\\%) & $\\rho$ per rank & CV$^2$ & mix (\\%) & TTFT hit (s) & TTFT miss (s) & p99 (s) & $W_q$ (s) & PK (s) & finite (s) \\\\\\midrule\n")
        out.write("\n".join(lines) + "\n\\bottomrule\\end{tabular}\\end{table*}\n")
    with open(os.path.join(a.tex_dir, "macros-e2.tex"), "w") as out:
        out.write("% generated by scripts/exp/paper_e2_tables.py; do not edit\n")
        out.write(macro("eTwoRuns", len(runs)))
        if runs:
            hit_lo = min(r["hit"] for r in runs)
            hit_hi = max(r["hit"] for r in runs)
            out.write(macro("eTwoHitLo", f"{100 * hit_lo:.0f}"))
            out.write(macro("eTwoHitHi", f"{100 * hit_hi:.0f}"))
            out.write(macro("eTwoNbarLo", f"{min(r['n_bar'] for r in runs):.1f}"))
            out.write(macro("eTwoNbarHi", f"{max(r['n_bar'] for r in runs):.1f}"))
            out.write(macro("eTwoRhoLo", f"{min(r['rho'] for r in runs):.2f}"))
            out.write(macro("eTwoRhoHi", f"{max(r['rho'] for r in runs):.2f}"))
            out.write(macro("eTwoCvLo", f"{min(r['cv2'] for r in runs):.1f}"))
            out.write(macro("eTwoCvHi", f"{max(r['cv2'] for r in runs):.1f}"))
            out.write(macro("eTwoShareLo", f"{100 * min(r['share'] for r in runs):.0f}"))
            out.write(macro("eTwoShareHi", f"{100 * max(r['share'] for r in runs):.0f}"))
            out.write(macro("eTwoTtftLo", f"{min(r['ttft'] for r in runs):.1f}"))
            out.write(macro("eTwoTtftHi", f"{max(r['ttft'] for r in runs):.1f}"))
            out.write(macro("eTwoRhoRankLo", f"{min(r.get('rho_lo', r['rho']) for r in runs):.2f}"))
            out.write(macro("eTwoRhoRankHi", f"{max(r.get('rho_hi', r['rho']) for r in runs):.2f}"))
            qs = [r["q_srv"] for r in runs if r.get("q_srv", float("nan")) == r.get("q_srv", float("nan"))]
            if qs:
                out.write(macro("eTwoWqLo", f"{min(qs):.1f}"))
                out.write(macro("eTwoWqHi", f"{max(qs):.1f}"))
            kvs = [r["kv_usage"] for r in runs if r.get("kv_usage", float("nan")) == r.get("kv_usage", float("nan"))]
            if kvs:
                out.write(macro("eTwoKvLo", f"{100 * min(kvs):.0f}"))
                out.write(macro("eTwoKvHi", f"{100 * max(kvs):.0f}"))
            out.write(macro("eTwoMissTtftLo", f"{min(r['ttft_miss'] for r in runs):.0f}"))
            out.write(macro("eTwoMissTtftHi", f"{max(r['ttft_miss'] for r in runs):.0f}"))
            out.write(macro("eTwoHitTtftLo", f"{min(r['ttft_hit'] for r in runs):.1f}"))
            out.write(macro("eTwoHitTtftHi", f"{max(r['ttft_hit'] for r in runs):.1f}"))
            out.write(macro("eTwoTailLo", f"{min(r['ttft_p99'] for r in runs):.0f}"))
            out.write(macro("eTwoTailHi", f"{max(r['ttft_p99'] for r in runs):.0f}"))
            ratio = [r["ttft_miss"] / r["ttft_hit"] for r in runs if r["ttft_hit"] > 0 and r["ttft_miss"] == r["ttft_miss"]]
            if ratio:
                out.write(macro("eTwoMissOverHitLo", f"{min(ratio):.0f}"))
                out.write(macro("eTwoMissOverHitHi", f"{max(ratio):.0f}"))
            out.write(macro("eTwoWobsLo", f"{min(r['w_obs'] for r in runs):.1f}"))
            out.write(macro("eTwoWobsHi", f"{max(r['w_obs'] for r in runs):.1f}"))
            fin_ratio = [r["w_fin"] / r["w_obs"] for r in runs if r["w_obs"] > 0]
            pk_ratio = [r["pk"] / r["w_obs"] for r in runs if r["w_obs"] > 0 and r["pk"] != float("inf")]
            if fin_ratio:
                out.write(macro("eTwoFinRatioLo", f"{min(fin_ratio):.2f}"))
                out.write(macro("eTwoFinRatioHi", f"{max(fin_ratio):.2f}"))
            if pk_ratio:
                out.write(macro("eTwoPkRatioLo", f"{min(pk_ratio):.1f}"))
                out.write(macro("eTwoPkRatioHi", f"{max(pk_ratio):.1f}"))
    print("wrote", a.tex_dir, "rows", len(lines))


if __name__ == "__main__":
    main()
