#!/usr/bin/env python3
"""E2b: the paper's tables and macros for the short-context replays (the PK
regime and the forced-miss price test), from the JSON written by
analyze_e2.py --warmup 90 --out (one entry per run) and analyze_price.py
--out (one file per spacing and seed). Never type these numbers into the
paper by hand.

  python3 scripts/exp/paper_e2b_tables.py data/exp/e2b/summary.json data/exp/e2b/price_*.json

Writes paper/exp/tab-e2b.tex (one row per run), paper/exp/tab-e2b-price.tex
(the price test per rank and summed: forced and unforced misses, loads,
L_P and its rise, the bracket with the head-of-line share of its lower
end, the finite-source price) and paper/exp/macros-e2b.tex.
"""
import argparse
import json
import os


def macro(name, value):
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def fmt_inf(x, nd=1):
    return "$\\infty$" if x == float("inf") else f"{x:.{nd}f}"


def tag_of(r):
    return os.path.basename(os.path.dirname(r["path"]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("summary")
    ap.add_argument("prices", nargs="*")
    ap.add_argument("--tex-dir", default="paper/exp")
    a = ap.parse_args()
    runs = [r for r in json.load(open(a.summary)) if r]
    runs.sort(key=lambda r: (-float(r["params"].get("spacing_s", 0) or 0), "m10" in tag_of(r), tag_of(r)))
    os.makedirs(a.tex_dir, exist_ok=True)
    lines = []
    for r in runs:
        tag = tag_of(r)
        delta = "10" if "m10" in tag else "0"
        seed = "1" if tag.endswith("_s1") else "0"
        nr = max(1, len(r.get("per_rank", [])))
        lam_rank = r["lam"] / nr
        n_rank = r["n_bar"] / nr
        rho_col = f"{r['rho_lo']:.2f}--{r['rho_hi']:.2f}"
        front = r["ttft"] - r.get("q_srv", 0.0) - r.get("pf_srv", 0.0)
        lines.append(
            f"{float(r['params']['spacing_s']):g} & {delta} & {seed} & {int(r['params'].get('sessions', 0))} & {n_rank:.1f} & {lam_rank:.2f} & {rho_col} & "
            f"{r.get('cv2_arr', float('nan')):.1f} & {100 * r['hit']:.0f} & {r['ttft_hit']:.2f} & {r['ttft_miss']:.2f} & {r['ttft_p99']:.1f} & "
            f"{r.get('q_srv', float('nan')):.2f} & {r.get('pf_srv', float('nan')):.2f} & {front:.2f} & {fmt_inf(r['pk'], 2)} & {r['w_fin']:.2f} & {100 * r.get('cap_share', 0.0):.0f} \\\\"
        )
    with open(os.path.join(a.tex_dir, "tab-e2b.tex"), "w") as out:
        out.write("% generated by scripts/exp/paper_e2b_tables.py; do not edit\n")
        out.write("\\begin{table*}[tbp]\\centering\\scriptsize\\setlength{\\tabcolsep}{3pt}\n")
        out.write(
            "\\caption{Short-context replay: open-loop replay of the trace derived from the long-context one (nine copies of the $37$ sessions, "
            "first prompt $2$k tokens, the source's appends scaled by $0.44$ so that the mean append is $\\approx 940$ tokens, contexts $2$k to $9$k at the median and up to $27$k, "
            "outputs of at most four tokens, the source's think times capped at $30$\\,s, a nonce per session so that no two share a prefix; sessions pinned round-robin over four ranks), "
            "one session every $s$ seconds, with a share $\\delta$ of follow-up turns forced to miss by a nonce at the head of that and every later prompt of the session (seed: the draw of nonces and forced turns). "
            "Sessions: replayed; $\\bar N$: mean live sessions per rank; $\\lambda$: turns per second per rank; $\\rho$: per-rank prefill utilisation from the fitted cost model; "
            "$\\mathrm{CV}^2_A$: interarrival $\\mathrm{CV}^2$ at a rank; hit: follow-up turns whose cached length is at least the previous prompt plus completion less one $512$-token sub-block "
            "(the server rounds the cached length down to the sub-block); TTFT of hits and misses (mean) and p99 over all turns; $W_q$, $S_{\\mathrm{srv}}$, front: the server's mean queueing time before the first prefill chunk, "
            "its prefill time, and the remainder of the mean TTFT (client and frontend); PK and finite: the open PK wait and the Markovian finite-source wait (Proposition~\\ref{prop:finite}) per rank; "
            "cap: share of the one-second samples with eight sequences running on the busiest rank. Window: from $90$\\,s after the first arrival to the last arrival.}"
            "\\label{tab:e2b}\n"
        )
        out.write("\\begin{tabular}{rrrrrrrrrrrrrrrrrr}\\toprule\n")
        out.write(
            "$s$ (s) & $\\delta$ (\\%) & seed & sessions & $\\bar N$ & $\\lambda$ (1/s) & $\\rho$ per rank & $\\mathrm{CV}^2_A$ & hit (\\%) & "
            "TTFT hit (s) & miss (s) & p99 (s) & $W_q$ (s) & $S_{\\mathrm{srv}}$ (s) & front (s) & PK (s) & finite (s) & cap (\\%) \\\\\\midrule\n"
        )
        out.write("\n".join(lines) + "\n\\bottomrule\\end{tabular}\\end{table*}\n")

    prices = [json.load(open(p)) for p in a.prices]
    prices.sort(key=lambda p: (-p["spacing_s"], p["forced"]))
    plines = []
    for p in prices:
        seed = "1" if p["forced"].endswith("_s1") else "0"
        for q in p["per_rank"] + [None]:
            t = q if q is not None else p["total"]
            name = str(q["rank"]) if q is not None else "all"
            rho = f"{q['rho']:.2f} & {q['rho1']:.2f}" if q is not None else "&"
            hol = 100 * t["hol"] / t["lo"] if t["lo"] > 0 else float("nan")
            byst = 100 * t["bystander"] / t["dl_p"] if t["dl_p"] > 0 else float("nan")
            row = (f"{p['spacing_s']:g} & {seed} & {name} & {t['n_forced']} & {t['n_unforced_b']}$\\to${t['n_unforced_f']} & {rho} & "
                   f"{t['l_p']:.2f} & {t['dl_p']:.2f} & {t['lo']:.2f} & {fmt_inf(t['hi'], 2)} & {hol:.0f} & {byst:.0f} & {t['fin']:.2f} \\\\")
            if q is None:
                row = row.replace("\\\\", "\\\\[1pt]")
            plines.append(row)
    with open(os.path.join(a.tex_dir, "tab-e2b-price.tex"), "w") as out:
        out.write("% generated by scripts/exp/paper_e2b_tables.py; do not edit\n")
        out.write("\\begin{table*}[tbp]\\centering\\scriptsize\\setlength{\\tabcolsep}{4pt}\n")
        out.write(
            "\\caption{The price test: the forced-miss arm against the baseline at the same spacing and seed (Table~\\ref{tab:e2b}), per rank and summed. "
            "Forced: turns forced to miss in the window; unforced: follow-up turns with nothing resident, baseline $\\to$ forced arm (the pool evicts more once the forced arm holds more KV); "
            "$\\rho$, $\\rho'$: the baseline's prefill load and the load the added work of every miss the change caused implies; "
            "$L_P$: baseline number in the prefill stage ($\\lambda$ times mean TTFT); $\\Delta L_P$: its observed rise; $[\\mathrm{lo},\\mathrm{hi}]$: the bracket of Proposition~\\ref{prop:price} "
            "from the baseline's $\\lambda$, $\\rho$ and PK wait and each miss's own hit and miss work, over the forced misses plus the unforced ones net of the baseline's; "
            "HOL: share of lo from the head-of-line term of~\\eqref{eq:price}; byst.: share of $\\Delta L_P$ borne by turns that did not miss; Fin.: the finite-source price of Proposition~\\ref{prop:finite}.}"
            "\\label{tab:e2b-price}\n"
        )
        out.write("\\begin{tabular}{rrrrrrrrrrrrrr}\\toprule\n")
        out.write("$s$ & seed & rank & forced & unforced & $\\rho$ & $\\rho'$ & $L_P$ & $\\Delta L_P$ & lo & hi & HOL (\\%) & byst. (\\%) & Fin. \\\\\\midrule\n")
        out.write("\n".join(plines) + "\n\\bottomrule\\end{tabular}\\end{table*}\n")

    with open(os.path.join(a.tex_dir, "macros-e2b.tex"), "w") as out:
        out.write("% generated by scripts/exp/paper_e2b_tables.py; do not edit\n")
        base_all = [r for r in runs if "m10" not in tag_of(r)]
        # Light arms (spacing >= 2 s) are the PK regime; the 1.5 s arm saturated.
        base = [r for r in base_all if float(r["params"]["spacing_s"]) >= 2.0]
        sat = [r for r in base_all if float(r["params"]["spacing_s"]) < 2.0]
        for r in sat:
            nr = max(1, len(r.get("per_rank", [])))
            out.write(macro("eTwobSatSpacing", f"{float(r['params']['spacing_s']):g}"))
            out.write(macro("eTwobSatRhoLo", f"{r['rho_lo']:.2f}"))
            out.write(macro("eTwobSatRhoHi", f"{r['rho_hi']:.2f}"))
            out.write(macro("eTwobSatWq", f"{r['q_srv']:.1f}"))
            out.write(macro("eTwobSatPk", f"{r['pk']:.1f}"))
            out.write(macro("eTwobSatNbarRank", f"{r['n_bar'] / nr:.0f}"))
            out.write(macro("eTwobSatCapShare", f"{100 * r.get('cap_share', 0.0):.0f}"))
            out.write(macro("eTwobSatItl", f"{r.get('itl_all', float('nan')):.1f}"))
            out.write(macro("eTwobSatMissShare", f"{100 * (1 - r['hit']):.0f}"))
        if base:
            out.write(macro("eTwobSpacingLo", f"{min(float(r['params']['spacing_s']) for r in base):g}"))
            out.write(macro("eTwobSpacingHi", f"{max(float(r['params']['spacing_s']) for r in base):g}"))
            out.write(macro("eTwobRhoLo", f"{min(r['rho_lo'] for r in base):.2f}"))
            out.write(macro("eTwobRhoHi", f"{max(r['rho_hi'] for r in base):.2f}"))
            out.write(macro("eTwobHitLo", f"{100 * min(r['hit'] for r in base):.0f}"))
            out.write(macro("eTwobHitHi", f"{100 * max(r['hit'] for r in base):.0f}"))
            out.write(macro("eTwobWqLo", f"{min(r['q_srv'] for r in base):.2f}"))
            out.write(macro("eTwobWqHi", f"{max(r['q_srv'] for r in base):.2f}"))
            out.write(macro("eTwobWobsLo", f"{min(r['w_obs'] for r in base):.2f}"))
            out.write(macro("eTwobWobsHi", f"{max(r['w_obs'] for r in base):.2f}"))
            pk_wq = [r["pk"] / r["q_srv"] for r in base if r.get("q_srv", 0) > 0]
            pk_wo = [r["pk"] / r["w_obs"] for r in base if r.get("w_obs", 0) > 0]
            out.write(macro("eTwobPkOverWqLo", f"{min(pk_wq):.1f}"))
            out.write(macro("eTwobPkOverWqHi", f"{max(pk_wq):.1f}"))
            out.write(macro("eTwobPkOverWobsLo", f"{min(pk_wo):.1f}"))
            out.write(macro("eTwobPkOverWobsHi", f"{max(pk_wo):.1f}"))
            fin_wq = [pr["w_fin"] / pr["queue_time_mean"] for r in base for pr in r["per_rank"] if pr.get("queue_time_mean", 0) > 0]
            out.write(macro("eTwobFinOverWqLo", f"{min(fin_wq):.1f}"))
            out.write(macro("eTwobFinOverWqHi", f"{max(fin_wq):.1f}"))
            cva = [r["cv2_arr"] for r in base if r.get("cv2_arr", float("nan")) == r.get("cv2_arr", float("nan"))]
            out.write(macro("eTwobCvArrLo", f"{min(cva):.1f}"))
            out.write(macro("eTwobCvArrHi", f"{max(cva):.1f}"))
            out.write(macro("eTwobPfOverEsLo", f"{min(r['pf_over_es'] for r in base):.2f}"))
            out.write(macro("eTwobPfOverEsHi", f"{max(r['pf_over_es'] for r in base):.2f}"))
            fr = [r["ttft"] - r["q_srv"] - r["pf_srv"] for r in base]
            out.write(macro("eTwobFrontLo", f"{min(fr):.2f}"))
            out.write(macro("eTwobFrontHi", f"{max(fr):.2f}"))
            out.write(macro("eTwobCapShareHi", f"{100 * max(r.get('cap_share', 0.0) for r in base):.1f}"))
        if prices:
            tots = [p["total"] for p in prices]
            out.write(macro("eTwobPriceRows", f"{len(prices)}"))
            out.write(macro("eTwobForcedLo", f"{min(t['n_forced'] for t in tots)}"))
            out.write(macro("eTwobForcedHi", f"{max(t['n_forced'] for t in tots)}"))
            extra = [t["n_unforced_f"] - t["n_unforced_b"] for t in tots]
            out.write(macro("eTwobExtraMissLo", f"{min(extra)}"))
            out.write(macro("eTwobExtraMissHi", f"{max(extra)}"))
            out.write(macro("eTwobDlLo", f"{min(t['dl_p'] for t in tots):.2f}"))
            out.write(macro("eTwobDlHi", f"{max(t['dl_p'] for t in tots):.2f}"))
            out.write(macro("eTwobLpLo", f"{min(t['l_p'] for t in tots):.2f}"))
            out.write(macro("eTwobLpHi", f"{max(t['l_p'] for t in tots):.2f}"))
            r_lo = [t["dl_p"] / t["lo"] for t in tots if t["lo"] > 0]
            r_hi = [t["dl_p"] / t["hi"] for t in tots if 0 < t["hi"] < float("inf")]
            out.write(macro("eTwobDlOverLoLo", f"{min(r_lo):.2f}"))
            out.write(macro("eTwobDlOverLoHi", f"{max(r_lo):.2f}"))
            out.write(macro("eTwobDlOverHiLo", f"{min(r_hi):.2f}"))
            out.write(macro("eTwobDlOverHiHi", f"{max(r_hi):.2f}"))
            out.write(macro("eTwobInBracket", f"{sum(1 for t in tots if t['lo'] <= t['dl_p'] <= t['hi'])}"))
            r_forced = [t["dl_p"] / t["lo_forced"] for t in tots if t["lo_forced"] > 0]
            out.write(macro("eTwobDlOverLoForcedHi", f"{max(r_forced):.2f}"))
            spread = [q["dl_p"] / q["lo"] for p in prices for q in p["per_rank"] if q["lo"] > 0]
            out.write(macro("eTwobSpreadLo", f"{min(spread):.2f}"))
            out.write(macro("eTwobSpreadHi", f"{max(spread):.2f}"))
            hol = [100 * t["hol"] / t["lo"] for t in tots if t["lo"] > 0]
            out.write(macro("eTwobHolShareLo", f"{min(hol):.0f}"))
            out.write(macro("eTwobHolShareHi", f"{max(hol):.0f}"))
            byst = [100 * t["bystander"] / t["dl_p"] for t in tots if t["dl_p"] > 0]
            out.write(macro("eTwobBystanderLo", f"{min(byst):.0f}"))
            out.write(macro("eTwobBystanderHi", f"{max(byst):.0f}"))
            # the queue's part of the rise against the service part: (dl - own) / own, with own = the added service rate
            q_over_s = [(t["dl_p"] - t["own"]) / t["own"] for t in tots if t["own"] > 0]
            out.write(macro("eTwobQueueOverServiceLo", f"{min(q_over_s):.1f}"))
            out.write(macro("eTwobQueueOverServiceHi", f"{max(q_over_s):.1f}"))
            lo_srv = [abs(t["lo_srv"] / t["lo"] - 1) * 100 for t in tots if t["lo"] > 0]
            out.write(macro("eTwobLoSrvDiffHi", f"{max(lo_srv):.0f}"))
            r_fin = [t["dl_p"] / t["fin"] for t in tots if t["fin"] > 0]
            out.write(macro("eTwobDlOverFinLo", f"{min(r_fin):.1f}"))
            out.write(macro("eTwobDlOverFinHi", f"{max(r_fin):.1f}"))
    print("wrote", a.tex_dir, "runs", len(runs), "price rows", len(prices))


if __name__ == "__main__":
    main()
