/-
# vLLM scheduler scenarios as theorems about seQ programs

Generated by `scripts/gen_seq_oracle.py` from the IR of seQ's oracle
scenarios (`tools/oracle/*.ir.json`) and the real vLLM v1 scheduler's
answers (`*.out.json`, `cache_trace.out.csv`: seQ `tools/vllm_oracle.py`
and `tools/vllm_replay_oracle.py`, upstream `ref/vllm` at 0c87a197).
Do not edit. The programs, the deployments and the workloads below are
translations of that IR, the same IR the seQ tests run.

Six scenarios run one request program, `vllmRequest` (seQ
`programs/vllm_request.seq`): wait until the arrival, hold a slot and the
KV blocks of the chunk the engine's budget leaves (admission needs room for
the whole prompt), prefill growing the hold, decode growing it. The
theorems say that the executable semantics gives, for every request, the
step of its first token and of its last token, and the number of
preemptions, that the real scheduler gives. The seventh, `vllmTurn` (seQ
`programs/vllm_replay.seq` on a unit step clock, the trace inlined as the
sessions' turns), is a multi-turn replay with a prefix cache: hits, a
partial hit and misses caused by eviction; its theorem gives, for every
turn, the send step, the time to first token, the latency and the cached
tokens that the real scheduler and KV-cache manager give. All are checked
by evaluation in the kernel (`decide +kernel`: no axiom beyond the
standard three).
-/
import ServingQueueTheory.SeqExec

set_option maxRecDepth 100000

namespace ServingQueueTheory
namespace SeqLang
namespace Oracle

open Exec

/-- The vLLM request program (seQ `programs/vllm_request.seq`), translated from its IR. Attributes: 2 = turn_no, 3 = new, 4 = out, 5 = think, 6 = more, 7 = forced, 8 = prompt, 9 = o, 10 = arrive. Observations: 0 = first, 1 = done. Pools: 0 = slots, 1 = kv. Stages: 0 = engine, 1 = gate. -/
def vllmRequest : Prog := [route|
  run 1 (x.attr 10);
  hold 0 (1), 1 (min (x.attr 8) x.budgetLeft) fits (x.attr 8) {
    run 0 prefill (x.attr 8) growing 1;
    observe 0 = x.now;
    run 0 decode ((x.attr 9) - 1) growing 1;
    done
  };
  observe 1 = x.now;
  stop]

theorem vllmRequest_wf : vllmRequest.wf = true := by decide

/-- (first-token steps, last-token steps, preemptions) of `vllmRequest`. -/
def outcome (D : Deployment) (ticks : ℕ) (w : Workload) :
    List (ℕ × ℕ) × List (ℕ × ℕ) × ℕ :=
  let m := Exec.runW D ticks w vllmRequest
  (observed m 0, observed m 1, m.preempts)

/-- seQ `tools/oracle/chunked.ir.json`: 3 requests, 1000 blocks of 16, budget 1024, 16 slots, chunk 0; the deployment and the workload are the IR's. -/
theorem vllm_chunked :
    outcome ⟨[⟨16, 1, true⟩, ⟨15984, 16, false⟩], 1024, 0⟩ 13
      ⟨[[(8, 3000), (9, 2), (10, 0)], [(8, 700), (9, 5), (10, 1)], [(8, 100), (9, 3), (10, 1)]], [], none, 0⟩ =
    ([(0, 3), (1, 4), (2, 4)], [(0, 4), (1, 8), (2, 6)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/hol.ir.json`: 3 requests, 11 blocks of 16, budget 1024, 16 slots, chunk 0; the deployment and the workload are the IR's. -/
theorem vllm_hol :
    outcome ⟨[⟨16, 1, true⟩, ⟨160, 16, false⟩], 1024, 0⟩ 25
      ⟨[[(8, 96), (9, 10), (10, 0)], [(8, 96), (9, 10), (10, 0)], [(8, 16), (9, 3), (10, 0)]], [], none, 0⟩ =
    ([(0, 1), (1, 11), (2, 11)], [(0, 10), (1, 20), (2, 13)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/longchunk.ir.json`: 2 requests, 1000 blocks of 16, budget 4096, 16 slots, chunk 1000; the deployment and the workload are the IR's. -/
theorem vllm_longchunk :
    outcome ⟨[⟨16, 1, true⟩, ⟨15984, 16, false⟩], 4096, 1000⟩ 9
      ⟨[[(8, 3000), (9, 2), (10, 0)], [(8, 3000), (9, 2), (10, 0)]], [], none, 0⟩ =
    ([(0, 3), (1, 3)], [(0, 4), (1, 4)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/mixed.ir.json`: 6 requests, 40 blocks of 16, budget 512, 4 slots, chunk 0; the deployment and the workload are the IR's. -/
theorem vllm_mixed :
    outcome ⟨[⟨4, 1, true⟩, ⟨624, 16, false⟩], 512, 0⟩ 105
      ⟨[[(8, 300), (9, 40), (10, 0)], [(8, 200), (9, 30), (10, 2)], [(8, 250), (9, 20), (10, 3)], [(8, 150), (9, 60), (10, 3)], [(8, 400), (9, 10), (10, 5)], [(8, 100), (9, 25), (10, 9)]], [], none, 0⟩ =
    ([(0, 1), (1, 3), (2, 33), (3, 41), (4, 53), (5, 63)], [(0, 40), (1, 32), (2, 52), (3, 100), (4, 62), (5, 87)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/preempt.ir.json`: 2 requests, 11 blocks of 16, budget 100, 16 slots, chunk 0; the deployment and the workload are the IR's. -/
theorem vllm_preempt :
    outcome ⟨[⟨16, 1, true⟩, ⟨160, 16, false⟩], 100, 0⟩ 65
      ⟨[[(8, 80), (9, 30), (10, 0)], [(8, 80), (9, 30), (10, 0)]], [], none, 0⟩ =
    ([(0, 1), (1, 31)], [(0, 30), (1, 60)], 1) := by
  decide +kernel

/-- seQ `tools/oracle/seqcap.ir.json`: 4 requests, 1000 blocks of 16, budget 1024, 2 slots, chunk 0; the deployment and the workload are the IR's. -/
theorem vllm_seqcap :
    outcome ⟨[⟨2, 1, true⟩, ⟨15984, 16, false⟩], 1024, 0⟩ 18
      ⟨[[(8, 1024), (9, 5), (10, 0)], [(8, 1024), (9, 5), (10, 0)], [(8, 1024), (9, 5), (10, 0)], [(8, 1024), (9, 5), (10, 0)]], [], none, 0⟩ =
    ([(0, 1), (1, 3), (2, 7), (3, 9)], [(0, 5), (1, 7), (2, 11), (3, 13)], 0) := by
  decide +kernel

/-! ### A multi-turn scenario with a prefix cache -/

/-- The vLLM replay program (seQ `programs/vllm_replay.seq`) on a unit step clock, translated from its IR. Attributes: 2 = turn_no, 3 = new, 4 = out, 5 = think, 6 = more, 7 = forced, 8 = prev, 9 = prevout, 10 = t0, 11 = prompt, 12 = hitmax, 13 = c. Observations: 0 = cached_tokens, 1 = prefix, 2 = sent, 3 = ttft, 4 = latency. Pools: 0 = kv, 1 = slots. Stages: 0 = engine, 1 = front, 2 = gate, 3 = tool. -/
def vllmTurn : Prog := [route|
  run 2 (x.serial * 3);
  set 8 = 0;
  set 9 = 0;
  turn;
  loop {
    set 10 = x.now;
    set 11 = x.attr 3;
    run 1 (0 + (0 * (x.attr 11)));
    set 12 = if (x.attr 7) ≠ 0 then 0 else (((min (x.attr 8) ((x.attr 11) - 1)) / 16) * 16);
    hold 1 (1), 0 ((min (x.cachedIn 0) (x.attr 12)) + (min ((x.attr 11) - (min (x.cachedIn 0) (x.attr 12))) x.budgetLeft)) fits (x.attr 11) reuse (x.attr 12) {
      set 13 = x.cached;
      observe 0 = x.attr 13;
      observe 1 = (x.attr 8) + (x.attr 9);
      observe 2 = x.attr 10;
      run 0 prefill ((x.attr 11) - (x.attr 13)) growing 0;
      observe 3 = x.now - (x.attr 10);
      run 0 decode ((x.attr 4) - 1) growing 0;
      done
    } cache (((x.attr 11) + (x.attr 4)) - 1);
    observe 4 = x.now - (x.attr 10);
    set 8 = x.attr 11;
    set 9 = x.attr 4;
    branch (x.attr 6) {
      run 3 (x.attr 5);
      turn;
      done
    } else {
      stop
    };
    done
  }]

theorem vllmTurn_wf : vllmTurn.wf = true := by decide

/-- seQ `tools/oracle/cache_trace.ir.json`: 3 sessions of the inlined trace
`cache_trace.csv`; the deployment and the workload are the IR's. Per turn:
send step, time to first token, latency, cached tokens at admission. -/
theorem vllm_cache_trace :
    let m := Exec.runW ⟨[⟨320, 16, false⟩, ⟨4, 1, true⟩], 64, 0⟩ 43
      ⟨[[], [], []], [[[(3, 100), (4, 3), (5, 2), (7, 0)], [(3, 150), (4, 3), (5, 2), (7, 0)], [(3, 210), (4, 3), (5, 0), (7, 0)]], [[(3, 120), (4, 3), (5, 2), (7, 0)], [(3, 180), (4, 3), (5, 2), (7, 0)], [(3, 230), (4, 3), (5, 0), (7, 0)]], [[(3, 90), (4, 3), (5, 2), (7, 0)], [(3, 140), (4, 3), (5, 2), (7, 0)], [(3, 200), (4, 3), (5, 0), (7, 0)]]], some 2, 6⟩ vllmTurn
    (observed m 2, observed m 3, observed m 4, observed m 0) =
      ([(0, 0), (0, 6), (0, 13), (1, 3), (1, 9), (1, 17), (2, 6), (2, 12), (2, 22)],
       [(0, 2), (0, 3), (0, 11), (1, 2), (1, 4), (1, 13), (2, 2), (2, 6), (2, 14)],
       [(0, 4), (0, 5), (0, 13), (1, 4), (1, 6), (1, 15), (2, 4), (2, 8), (2, 16)],
       [(0, 0), (0, 96), (0, 0), (1, 0), (1, 64), (1, 0), (2, 0), (2, 0), (2, 0)]) := by
  decide +kernel

end Oracle
end SeqLang
end ServingQueueTheory
