/-
# vLLM scheduler scenarios as theorems about seQ programs

Generated by `scripts/gen_seq_oracle.py` from seQ `tools/oracle/*.json`
(the scenarios) and `*.out.json` (what the real vLLM v1 scheduler does:
seQ `tools/vllm_oracle.py`, upstream `ref/vllm` at 0c87a197). Do not edit.

Each scenario is a deployment (a request-slot pool served by the engine, a
KV pool of blocks, the engine's budget and chunk cap) and a set of requests
(prompt, output tokens, arrival step). Every request runs the same seQ
program, `vllmRequest`: wait until its arrival, hold a slot and the KV
blocks of the chunk the engine's budget leaves (admission needs room for
the whole prompt), prefill growing the hold, decode growing it. The
theorems say that the executable semantics gives, for every request, the
step of its first token and of its last token, and the number of
preemptions, that the real scheduler gives. They are checked by evaluation
in the kernel (`decide +kernel`: no axiom beyond the standard three).
-/
import ServingQueueTheory.SeqExec

set_option maxRecDepth 100000

namespace ServingQueueTheory
namespace SeqLang
namespace Oracle

open Exec

/-- Attribute slots: 0 = prompt tokens, 1 = output tokens, 2 = arrival
step. Observations: 0 = first-token step, 1 = last-token step. Pools:
0 = request slots (served by the engine), 1 = KV blocks. Stages: 0 = the
engine, 1 = a delay. -/
def vllmRequest : Prog := [route|
  run 1 (x.attr 2);
  hold 0 (1), 1 (min (x.attr 0) x.budgetLeft) fits (x.attr 0) {
    run 0 prefill (x.attr 0) growing 1;
    observe 0 = x.now;
    run 0 decode (x.attr 1 - 1) growing 1;
    done
  };
  observe 1 = x.now;
  stop]

theorem vllmRequest_wf : vllmRequest.wf = true := by decide

/-- A vLLM engine: `max_num_seqs` slots, `num_blocks` blocks of `bs` tokens
(one is the null block), `max_num_batched_tokens`, chunk cap. -/
def engine (maxSeqs blocks bs budget chunk : ℕ) : Deployment :=
  ⟨[⟨maxSeqs, 1, true⟩, ⟨(blocks - 1) * bs, bs, false⟩], budget, chunk⟩

/-- Request attributes from a table of (prompt, out, arrive). -/
def reqs (t : List (ℕ × ℕ × ℕ)) (i slot : ℕ) : ℕ :=
  match t[i]?, slot with
  | some (p, _, _), 0 => p
  | some (_, o, _), 1 => o
  | some (_, _, a), 2 => a
  | _, _ => 0

/-- (first-token steps, last-token steps, preemptions). -/
def outcome (D : Deployment) (ticks : ℕ) (t : List (ℕ × ℕ × ℕ)) :
    List (ℕ × ℕ) × List (ℕ × ℕ) × ℕ :=
  let m := Exec.run D ticks t.length (reqs t) vllmRequest
  (observed m 0, observed m 1, m.preempts)

/-- seQ `tools/oracle/chunked.json`: 3 requests, 1000 blocks of 16, budget 1024, 16 slots, chunk 0. -/
theorem vllm_chunked :
    outcome (engine 16 1000 16 1024 0) 13
      [(3000, 2, 0), (700, 5, 1), (100, 3, 1)] =
    ([(0, 3), (1, 4), (2, 4)], [(0, 4), (1, 8), (2, 6)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/hol.json`: 3 requests, 11 blocks of 16, budget 1024, 16 slots, chunk 0. -/
theorem vllm_hol :
    outcome (engine 16 11 16 1024 0) 25
      [(96, 10, 0), (96, 10, 0), (16, 3, 0)] =
    ([(0, 1), (1, 11), (2, 11)], [(0, 10), (1, 20), (2, 13)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/longchunk.json`: 2 requests, 1000 blocks of 16, budget 4096, 16 slots, chunk 1000. -/
theorem vllm_longchunk :
    outcome (engine 16 1000 16 4096 1000) 9
      [(3000, 2, 0), (3000, 2, 0)] =
    ([(0, 3), (1, 3)], [(0, 4), (1, 4)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/mixed.json`: 6 requests, 40 blocks of 16, budget 512, 4 slots, chunk 0. -/
theorem vllm_mixed :
    outcome (engine 4 40 16 512 0) 105
      [(300, 40, 0), (200, 30, 2), (250, 20, 3), (150, 60, 3), (400, 10, 5), (100, 25, 9)] =
    ([(0, 1), (1, 3), (2, 33), (3, 41), (4, 53), (5, 63)], [(0, 40), (1, 32), (2, 52), (3, 100), (4, 62), (5, 87)], 0) := by
  decide +kernel

/-- seQ `tools/oracle/preempt.json`: 2 requests, 11 blocks of 16, budget 100, 16 slots, chunk 0. -/
theorem vllm_preempt :
    outcome (engine 16 11 16 100 0) 65
      [(80, 30, 0), (80, 30, 0)] =
    ([(0, 1), (1, 31)], [(0, 30), (1, 60)], 1) := by
  decide +kernel

/-- seQ `tools/oracle/seqcap.json`: 4 requests, 1000 blocks of 16, budget 1024, 2 slots, chunk 0. -/
theorem vllm_seqcap :
    outcome (engine 2 1000 16 1024 0) 18
      [(1024, 5, 0), (1024, 5, 0), (1024, 5, 0), (1024, 5, 0)] =
    ([(0, 1), (1, 3), (2, 7), (3, 9)], [(0, 5), (1, 7), (2, 11), (3, 13)], 0) := by
  decide +kernel

/-! ### A multi-turn scenario with a prefix cache

seQ `tools/oracle/cache_trace.jsonl`: three sessions of 3 turns, every
prompt extending the previous one, 3 output tokens, 2 steps of think time,
on 20 blocks of 16 tokens, a budget of 64 and 4 slots. The real vLLM
scheduler's answer (`cache_trace.out.csv`) has hits, a partial hit and
misses caused by eviction. The seQ program is the vLLM engine's rule for
a turn: the scheduler admits (`viaEngine`) with the whole prompt as the
gate and the first chunk allocated; the turn reuses at most the full blocks
of its previous prompt, the rest of its cached entry stays dead; every
computed token is cached; a finished session's cache stays. Attributes:
0 = turn index, 1 = previous prompt. Observations: 0 = first-token step,
1 = last-token step, 2 = cached tokens at admission. -/

def cachePrompts : List (List ℕ) := [[100, 150, 210], [120, 180, 230], [90, 140, 200]]
def cacheArrive : List ℕ := [0, 3, 6]
def cachePrompt (x : Env) : ℕ := (cachePrompts.getD x.serial []).getD (x.attr 0) 0
def cacheHitMax (x : Env) : ℕ := min (x.attr 1) (cachePrompt x - 1) / 16 * 16

def vllmTurn : Prog := [route|
  run 1 (cacheArrive.getD x.serial 0);
  loop {
    hold 0 (1), 1 (min (x.cachedIn 1) (cacheHitMax x)
        + min (cachePrompt x - min (x.cachedIn 1) (cacheHitMax x)) x.budgetLeft)
        fits (cachePrompt x) reuse (cacheHitMax x) {
      run 0 prefill (cachePrompt x - x.cached) growing 1;
      observe 0 = x.now;
      run 0 decode (2) growing 1;
      done
    } cache (cachePrompt x + 2);
    observe 1 = x.now;
    observe 2 = x.cached;
    set 1 = cachePrompt x;
    set 0 = x.attr 0 + 1;
    branch (if x.attr 0 < 3 then 1 else 0) { run 1 (2); done } else { stop };
    done
  }]

theorem vllm_cache_trace :
    let m := Exec.run (engine 4 21 16 64 0) 45 3 (fun _ _ => 0) vllmTurn
    (observed m 0, observed m 1, observed m 2) =
      ([(0, 2), (0, 9), (0, 24), (1, 5), (1, 13), (1, 30), (2, 8), (2, 18), (2, 36)], [(0, 4), (0, 11), (0, 26), (1, 7), (1, 15), (1, 32), (2, 10), (2, 20), (2, 38)], [(0, 0), (0, 96), (0, 0), (1, 0), (1, 64), (1, 0), (2, 0), (2, 0), (2, 0)]) := by
  decide +kernel

end Oracle
end SeqLang
end ServingQueueTheory
