#!/usr/bin/env python3
"""Generate lean/ServingQueueTheory/SeqOracle.lean from the vLLM scheduler
scenarios of the pinned seQ release (.seq/src/tools/oracle/*.json, checked
out by scripts/fetch_seq.sh) and the real scheduler's answers
*.out.json: one theorem per scenario stating that the seQ program of the
vLLM engine, run by the executable semantics (lean/ServingQueueTheory/SeqExec.lean), gives the
same first-token step, last-token step and preemption count for every
request. `--check` fails if the committed file is stale."""
import json
import os
import sys

ROOT = os.path.join(os.path.dirname(__file__), "..")
ODIR = os.path.join(ROOT, ".seq", "src", "tools", "oracle")
OUT = os.path.join(ROOT, "lean", "ServingQueueTheory", "SeqOracle.lean")

HEAD = '''/-
# vLLM scheduler scenarios as theorems about seQ programs

Generated by `scripts/gen_seq_oracle.py` from seQ `tools/oracle/*.json`
(the scenarios) and `*.out.json` (what the real vLLM v1 scheduler does:
seQ `tools/vllm_oracle.py`, upstream `ref/vllm` at 0c87a197). Do not edit.

Each scenario is a deployment (a request-slot pool served by the engine, a
KV pool of blocks, the engine's budget and chunk cap) and a set of requests
(prompt, output tokens, arrival step). Every request runs the same seQ
program, `vllmRequest`: wait until its arrival, hold a slot and the KV
blocks of the chunk the engine's budget leaves (admission needs room for
the whole prompt), prefill growing the hold, decode growing it. The
theorems say that the executable semantics gives, for every request, the
step of its first token and of its last token, and the number of
preemptions, that the real scheduler gives. They are checked by evaluation
in the kernel (`decide +kernel`: no axiom beyond the standard three).
-/
import ServingQueueTheory.SeqExec

set_option maxRecDepth 100000

namespace ServingQueueTheory
namespace SeqLang
namespace Oracle

open Exec

/-- Attribute slots: 0 = prompt tokens, 1 = output tokens, 2 = arrival
step. Observations: 0 = first-token step, 1 = last-token step. Pools:
0 = request slots (served by the engine), 1 = KV blocks. Stages: 0 = the
engine, 1 = a delay. -/
def vllmRequest : Prog := [route|
  run 1 (x.attr 2);
  hold 0 (1), 1 (min (x.attr 0) x.budgetLeft) fits (x.attr 0) {
    run 0 prefill (x.attr 0) growing 1;
    observe 0 = x.now;
    run 0 decode (x.attr 1 - 1) growing 1;
    done
  };
  observe 1 = x.now;
  stop]

theorem vllmRequest_wf : vllmRequest.wf = true := by decide

/-- A vLLM engine: `max_num_seqs` slots, `num_blocks` blocks of `bs` tokens
(one is the null block), `max_num_batched_tokens`, chunk cap. -/
def engine (maxSeqs blocks bs budget chunk : ℕ) : Deployment :=
  ⟨[⟨maxSeqs, 1, true⟩, ⟨(blocks - 1) * bs, bs, false⟩], budget, chunk⟩

/-- Request attributes from a table of (prompt, out, arrive). -/
def reqs (t : List (ℕ × ℕ × ℕ)) (i slot : ℕ) : ℕ :=
  match t[i]?, slot with
  | some (p, _, _), 0 => p
  | some (_, o, _), 1 => o
  | some (_, _, a), 2 => a
  | _, _ => 0

/-- (first-token steps, last-token steps, preemptions). -/
def outcome (D : Deployment) (ticks : ℕ) (t : List (ℕ × ℕ × ℕ)) :
    List (ℕ × ℕ) × List (ℕ × ℕ) × ℕ :=
  let m := Exec.run D ticks t.length (reqs t) vllmRequest
  (observed m 0, observed m 1, m.preempts)
'''


def gen():
    out = [HEAD]
    for f in sorted(os.listdir(ODIR)):
        if not f.endswith(".json") or f.endswith(".out.json"):
            continue
        name = f[:-5]
        if not os.path.exists(os.path.join(ODIR, name + ".out.json")):
            continue  # not a scenario (e.g. a100_engine.json)
        sc = json.load(open(os.path.join(ODIR, f)))
        ans = json.load(open(os.path.join(ODIR, name + ".out.json")))
        n = len(sc["requests"])
        first = sorted((int(k), v) for k, v in ans["first"].items())
        done = sorted((int(k), v) for k, v in ans["done"].items())
        ticks = max([v for _, v in done] + [0]) + 5
        tbl = ", ".join(f"({r['prompt']}, {r['out']}, {r.get('arrive', 0)})" for r in sc["requests"])
        fs = ", ".join(f"({k}, {v})" for k, v in first)
        ds = ", ".join(f"({k}, {v})" for k, v in done)
        out.append(f'''
/-- seQ `tools/oracle/{f}`: {n} requests, {sc["num_blocks"]} blocks of {sc["block_size"]}, budget {sc["budget"]}, {sc["max_seqs"]} slots, chunk {sc.get("chunk", 0)}. -/
theorem vllm_{name} :
    outcome (engine {sc["max_seqs"]} {sc["num_blocks"]} {sc["block_size"]} {sc["budget"]} {sc.get("chunk", 0)}) {ticks}
      [{tbl}] =
    ([{fs}], [{ds}], {ans["preemptions"]}) := by
  decide +kernel
''')
    out.append(gen_cache())
    out.append("\nend Oracle\nend SeqLang\nend ServingQueueTheory\n")
    return "".join(out)


def gen_cache():
    """The multi-turn prefix-cache scenario: cache_trace.jsonl answered by the
    real scheduler and KV-cache manager on the step clock (cache_trace.out.csv,
    tools/vllm_replay_oracle.py with a unit step cost)."""
    sess = [json.loads(l) for l in open(os.path.join(ODIR, "cache_trace.jsonl")) if l.strip()]
    rows = {}
    for l in open(os.path.join(ODIR, "cache_trace.out.csv")).read().splitlines()[1:]:
        s, k, sent, first, done, prompt, cached, o = l.split(",")
        rows[(int(s), int(k))] = (int(float(first)), int(float(done)), int(cached))
    tbl = "[" + ", ".join("[" + ", ".join(str(q["in"]) for q in x["requests"]) + "]" for x in sess) + "]"
    arr = "[" + ", ".join(str(int(x["arrive"])) for x in sess) + "]"
    keys = sorted(rows)
    first = ", ".join(f"({s}, {rows[(s, k)][0]})" for s, k in keys)
    done = ", ".join(f"({s}, {rows[(s, k)][1]})" for s, k in keys)
    cached = ", ".join(f"({s}, {rows[(s, k)][2]})" for s, k in keys)
    turns = len(sess[0]["requests"])
    return f'''
/-! ### A multi-turn scenario with a prefix cache

seQ `tools/oracle/cache_trace.jsonl`: three sessions of {turns} turns, every
prompt extending the previous one, 3 output tokens, 2 steps of think time,
on 20 blocks of 16 tokens, a budget of 64 and 4 slots. The real vLLM
scheduler's answer (`cache_trace.out.csv`) has hits, a partial hit and
misses caused by eviction. The seQ program is the vLLM engine's rule for
a turn: the scheduler admits (`viaEngine`) with the whole prompt as the
gate and the first chunk allocated; the turn reuses at most the full blocks
of its previous prompt, the rest of its cached entry stays dead; every
computed token is cached; a finished session's cache stays. Attributes:
0 = turn index, 1 = previous prompt. Observations: 0 = first-token step,
1 = last-token step, 2 = cached tokens at admission. -/

def cachePrompts : List (List ℕ) := {tbl}
def cacheArrive : List ℕ := {arr}
def cachePrompt (x : Env) : ℕ := (cachePrompts.getD x.serial []).getD (x.attr 0) 0
def cacheHitMax (x : Env) : ℕ := min (x.attr 1) (cachePrompt x - 1) / 16 * 16

def vllmTurn : Prog := [route|
  run 1 (cacheArrive.getD x.serial 0);
  loop {{
    hold 0 (1), 1 (min (x.cachedIn 1) (cacheHitMax x)
        + min (cachePrompt x - min (x.cachedIn 1) (cacheHitMax x)) x.budgetLeft)
        fits (cachePrompt x) reuse (cacheHitMax x) {{
      run 0 prefill (cachePrompt x - x.cached) growing 1;
      observe 0 = x.now;
      run 0 decode (2) growing 1;
      done
    }} cache (cachePrompt x + 2);
    observe 1 = x.now;
    observe 2 = x.cached;
    set 1 = cachePrompt x;
    set 0 = x.attr 0 + 1;
    branch (if x.attr 0 < {turns} then 1 else 0) {{ run 1 (2); done }} else {{ stop }};
    done
  }}]

theorem vllm_cache_trace :
    let m := Exec.run (engine 4 21 16 64 0) 45 3 (fun _ _ => 0) vllmTurn
    (observed m 0, observed m 1, observed m 2) =
      ([{first}], [{done}], [{cached}]) := by
  decide +kernel
'''



if __name__ == "__main__":
    txt = gen()
    if "--check" in sys.argv:
        if open(OUT).read() != txt:
            print("STALE: lean/ServingQueueTheory/SeqOracle.lean; run scripts/gen_seq_oracle.py")
            sys.exit(1)
        print("SeqOracle.lean is current")
    else:
        open(OUT, "w").write(txt)
        print("wrote", OUT)
