name = "ServingQueueTheory"
version = "0.1.0"
defaultTargets = ["ServingQueueTheory"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[lean_lib]]
name = "ServingQueueTheory"
